'use strict';
/* ================================================================
   THREAT LEVEL TRIVIA — Static Data
   Questions, quote reactions, categories, tag suggestions
   ================================================================ */

const QUESTIONS = [

  // ── CHARACTERS ────────────────────────────────────────────────
  { id: 1, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who is the Regional Manager of Dunder Mifflin's Scranton branch for most of the series?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Jim Halpert", "Andy Bernard"] },
  { id: 2, category: "Characters", difficulty: "Easy", tags: [],
    question: "What vegetable does Dwight Schrute grow on his farm?",
    answer: "Beets",
    distractors: ["Turnips", "Potatoes", "Radishes"] },
  { id: 3, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who is Jim Halpert's primary prank target throughout the series?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Andy Bernard", "Stanley Hudson"] },
  { id: 4, category: "Characters", difficulty: "Easy", tags: [],
    question: "What is Dwight Schrute's official job title?",
    answer: "Assistant to the Regional Manager",
    distractors: ["Assistant Regional Manager", "Sales Associate", "Office Administrator"] },
  { id: 5, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who plays Michael Scott in The Office?",
    answer: "Steve Carell",
    distractors: ["Rainn Wilson", "John Krasinski", "Ed Helms"] },
  { id: 6, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who plays Jim Halpert?",
    answer: "John Krasinski",
    distractors: ["Steve Carell", "B.J. Novak", "Ed Helms"] },
  { id: 7, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who plays Dwight Schrute?",
    answer: "Rainn Wilson",
    distractors: ["John Krasinski", "Ed Helms", "Craig Robinson"] },
  { id: 8, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who plays Pam Beesly?",
    answer: "Jenna Fischer",
    distractors: ["Angela Kinsey", "Mindy Kaling", "Ellie Kemper"] },
  { id: 9, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who handles HR at Dunder Mifflin, often to Michael's disdain?",
    answer: "Toby Flenderson",
    distractors: ["Holly Flax", "David Wallace", "Jan Levinson"] },
  { id: 10, category: "Characters", difficulty: "Easy", tags: [],
    question: "What is the name of Kevin Malone's band?",
    answer: "Scrantonicity",
    distractors: ["Here Comes Treble", "The Hunted", "Dunder Mifflinaires"] },
  { id: 11, category: "Characters", difficulty: "Easy", tags: [],
    question: "What nickname does Andy Bernard give Jim Halpert?",
    answer: "Big Tuna",
    distractors: ["Jimothy", "Halps", "Slim Jim"] },
  { id: 12, category: "Characters", difficulty: "Easy", tags: [],
    question: "What temp-turned-executive started his career at Dunder Mifflin at the bottom?",
    answer: "Ryan Howard",
    distractors: ["Toby Flenderson", "Kelly Kapoor", "Andy Bernard"] },
  { id: 13, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who leads the Party Planning Committee with her love of cats and stern demeanor?",
    answer: "Angela Martin",
    distractors: ["Phyllis Vance", "Pam Beesly", "Kelly Kapoor"] },
  { id: 14, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is the name of Dwight's cousin who lives on the farm with him?",
    answer: "Mose",
    distractors: ["Jeb", "Fannie", "Zeke"] },
  { id: 15, category: "Characters", difficulty: "Medium", tags: [],
    question: "What car does Michael Scott drive?",
    answer: "Chrysler Sebring",
    distractors: ["PT Cruiser", "Toyota Camry", "Ford Taurus"] },
  { id: 16, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is Angela Martin's middle name?",
    answer: "Noel",
    distractors: ["Marie", "Grace", "Louise"] },
  { id: 17, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is the name of Angela's cat that Dwight kills?",
    answer: "Sprinkles",
    distractors: ["Mr. Ash", "Princess Lady", "Bandit"] },
  { id: 18, category: "Characters", difficulty: "Medium", tags: [],
    question: "Who portrays the obnoxious traveling salesman Todd Packer?",
    answer: "David Koechner",
    distractors: ["Rob Riggle", "Will Ferrell", "Craig Robinson"] },
  { id: 19, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is Michael Scott's embarrassing online dating username?",
    answer: "Littlekidlover",
    distractors: ["Date_Mike", "RegionalManager99", "BestBoss2005"] },
  { id: 20, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is the name of Stanley Hudson's daughter?",
    answer: "Melissa",
    distractors: ["Jessica", "Samantha", "Jasmine"] },
  { id: 21, category: "Characters", difficulty: "Medium", tags: [],
    question: "Who plays Robert California?",
    answer: "James Spader",
    distractors: ["Idris Elba", "Will Ferrell", "Kathy Bates"] },
  { id: 22, category: "Characters", difficulty: "Medium", tags: [],
    question: "Why does Andy call Jim 'Big Tuna'?",
    answer: "He saw Jim eating a tuna fish sandwich on his first day at the Stamford branch",
    distractors: ["Jim once won a tuna fishing contest", "Jim's favorite restaurant was a seafood place near the office", "Jim wore a tuna-themed shirt on his first day"] },
  { id: 23, category: "Characters", difficulty: "Medium", tags: [],
    question: "What kids' show did Michael Scott star in before working at Dunder Mifflin?",
    answer: "Fundle Bundle",
    distractors: ["Puppet Pals", "Sunny Side Up", "Kids' Corner"] },
  { id: 24, category: "Characters", difficulty: "Medium", tags: [],
    question: "What profession is Bob Vance known for?",
    answer: "Refrigeration (owner of Vance Refrigeration)",
    distractors: ["Construction (owner of Vance Construction)", "Plumbing (owner of Vance Plumbing)", "Lumber (owner of Vance Lumber)"] },
  { id: 25, category: "Characters", difficulty: "Medium", tags: [],
    question: "Who was the first employee in the office to find out about Jim's crush on Pam?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Kevin Malone", "Oscar Martinez"] },
  { id: 26, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is Dwight Schrute's Second Life avatar name?",
    answer: "Dwight Shelford",
    distractors: ["Dwight Schrute II", "RecyclopsX", "Dwight Halperton"] },
  { id: 27, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is the name of Michael Scott's ex-girlfriend who was a realtor?",
    answer: "Carol Stills",
    distractors: ["Jan Levinson", "Holly Flax", "Donna Newton"] },
  { id: 28, category: "Characters", difficulty: "Hard", tags: [],
    question: "What waitress's name does the group meet at the Japanese steakhouse (Benihana)?",
    answer: "Cindy",
    distractors: ["Katie", "Nikki", "Jessica"] },
  { id: 29, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is Kelly Kapoor's middle name?",
    answer: "Rajnigandha",
    distractors: ["Priya", "Lakshmi", "Ananya"] },
  { id: 30, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is Dwight's great-grandfather's name?",
    answer: "Dwide Schrute",
    distractors: ["Dwart Schrute", "Dwald Schrute", "Dwight Schrute Sr."] },

  // ── EPISODES & EVENTS ─────────────────────────────────────────
  { id: 31, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What is the name of Dunder Mifflin's annual awards ceremony?",
    answer: "The Dundies",
    distractors: ["The Scranties", "The Dunder Awards", "The Paper Cups"] },
  { id: 32, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What does Jim famously put Dwight's stapler in?",
    answer: "Jell-O",
    distractors: ["A vending machine", "A cake", "A block of ice"] },
  { id: 33, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "How does Michael Scott burn his foot in the episode 'The Injury'?",
    answer: "He steps on his George Foreman grill",
    distractors: ["He spills hot coffee on it", "He kicks a space heater", "He drops a hot panini press on it"] },
  { id: 34, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What is the name of the second episode of the first season?",
    answer: "Diversity Day",
    distractors: ["Health Care", "The Alliance", "Hot Girl"] },
  { id: 35, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What season did Steve Carell leave The Office?",
    answer: "Season 7",
    distractors: ["Season 6", "Season 8", "Season 5"] },
  { id: 36, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "How many total episodes does The Office have?",
    answer: "201",
    distractors: ["188", "212", "196"] },
  { id: 37, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What date did the pilot episode air?",
    answer: "March 24, 2005",
    distractors: ["September 10, 2004", "January 15, 2005", "May 6, 2005"] },
  { id: 38, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In the 'Diversity Day' episode, whose stand-up routine does Michael imitate?",
    answer: "Chris Rock",
    distractors: ["Dave Chappelle", "Eddie Murphy", "Richard Pryor"] },
  { id: 39, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In 'The Injury,' where does Jim pretend to take a concussed Dwight to recover?",
    answer: "Chuck E. Cheese",
    distractors: ["Dave & Buster's", "The hospital", "Hooters"] },
  { id: 40, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In the 'Product Recall' episode, who does Jim dress up as to prank Dwight?",
    answer: "Dwight (himself)",
    distractors: ["Michael Scott", "Stanley Hudson", "Andy Bernard"] },
  { id: 41, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In the 'Christmas Party' episode, who does Kevin get for Secret Santa?",
    answer: "Himself",
    distractors: ["Angela", "Michael", "Oscar"] },
  { id: 42, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In which episode does Michael Scott accidentally hit Meredith with his car?",
    answer: "Fun Run",
    distractors: ["Safety Training", "The Injury", "Beach Games"] },
  { id: 43, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In what season is Andy Bernard first introduced?",
    answer: "Season 3",
    distractors: ["Season 2", "Season 4", "Season 5"] },
  { id: 44, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In 'The Coup,' what high school movie does Michael watch for Movie Mondays?",
    answer: "Varsity Blues",
    distractors: ["Armageddon", "Entourage", "The Breakfast Club"] },
  { id: 45, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In which episode does Michael Scott pretend to fire Pam as a prank?",
    answer: "The Pilot",
    distractors: ["Diversity Day", "Hot Girl", "The Alliance"] },
  { id: 46, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In 'The Job,' what color does Dwight paint his office when he becomes interim Regional Manager?",
    answer: "Black",
    distractors: ["Red", "Dark Brown", "Navy Blue"] },
  { id: 47, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "What is the name of the episode where Dwight stages a fire drill and causes Stanley to have a heart attack?",
    answer: "Stress Relief",
    distractors: ["The Fire", "Safety Training", "Fun Run"] },
  { id: 48, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In what episode does Jim propose to Pam?",
    answer: "Weight Loss",
    distractors: ["Goodbye, Toby", "Niagara", "Crime Aid"] },
  { id: 49, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "What was the event called when Michael took everyone on a boat cruise in season two?",
    answer: "Booze Cruise",
    distractors: ["Office Cruise", "Party Boat", "Dunder Cruise"] },
  { id: 50, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What does Stanley secretly tell his wife to buy over the phone after Michael announces $1,000 raises in 'Dwight's Speech'?",
    answer: "Wallpaper",
    distractors: ["A new couch", "Curtains", "A flat screen TV"] },
  { id: 51, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "In 'Conflict Resolution,' what two things does Jim label on Dwight's fake security badge?",
    answer: "'Security risk' and 'Fart' as his middle name",
    distractors: ["'Extremely dangerous' and 'Karate expert'", "'Authorized idiot' and 'Beet juice' as blood type", "'Top secret clearance' and 'Weapons grade stupidity'"] },
  { id: 52, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "In 'The Merger,' which Stamford branch employee is the first to quit?",
    answer: "Tony",
    distractors: ["Karen Filippelli", "Hannah", "Martin"] },
  { id: 53, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "In 'Office Olympics,' what scent does Kevin claim the Eternal Burning of Competition candle smells like?",
    answer: "Cookies",
    distractors: ["Vanilla", "Cinnamon", "Burnt popcorn"] },
  { id: 54, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "While Pam reviews last year's Dundie Awards video, what is Roy eating?",
    answer: "Chicken Crispers",
    distractors: ["Hot wings", "Pizza", "Nachos"] },
  { id: 55, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "In 'Drug Testing,' who does Jim catch overhearing him do an impression while coming out of the bathroom?",
    answer: "Stanley",
    distractors: ["Dwight", "Ryan", "Toby"] },

  // ── QUOTES ────────────────────────────────────────────────────
  { id: 56, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Which character is known for saying 'That's what she said'?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Jim Halpert", "Kevin Malone"] },
  { id: 57, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Which character says 'Bears, beets, Battlestar Galactica'?",
    answer: "Jim Halpert (impersonating Dwight)",
    distractors: ["Dwight Schrute", "Michael Scott", "Andy Bernard"] },
  { id: 58, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Who says: 'I am ready to face any challenges that might be foolish enough to face me'?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Andy Bernard", "Robert California"] },
  { id: 59, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Michael Scott says he is 'not superstitious, but...' — how does he finish that sentence?",
    answer: "'I am a little stitious'",
    distractors: ["'I am a little nervous'", "'I am pretty cautious'", "'I believe in coincidences'"] },
  { id: 60, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Who teaches Michael the phrases 'Fleece it out' and 'Going mach five' as fake slang?",
    answer: "Darryl Philbin",
    distractors: ["Stanley Hudson", "Ryan Howard", "Kevin Malone"] },
  { id: 61, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Which character says: 'Reject a woman and she will never let it go. One of the many defects of their kind. Also weak arms.'?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Robert California", "Ryan Howard"] },
  { id: 62, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Which character says: 'I know that patience and loyalty are good and virtuous traits, but sometimes I just think you need to grow a pair.'?",
    answer: "Angela Martin",
    distractors: ["Jan Levinson", "Kelly Kapoor", "Phyllis Vance"] },
  { id: 63, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Which character says: 'I never really thought about death until Princess Diana died. That was the saddest funeral ever, that and my sister's.'?",
    answer: "Kelly Kapoor",
    distractors: ["Michael Scott", "Ryan Howard", "Meredith Palmer"] },
  { id: 64, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Which character says 'You miss 100% of the shots you don't take — Wayne Gretzky' and is credited as having said it?",
    answer: "Michael Scott (he attributes it to Wayne Gretzky)",
    distractors: ["Dwight Schrute", "Jim Halpert", "Andy Bernard"] },
  { id: 65, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Which character says: 'In the '60s I made love to many, many women, often outdoors in the mud and rain... and it's possible a man slipped in.'?",
    answer: "Creed Bratton",
    distractors: ["Michael Scott", "Meredith Palmer", "Robert California"] },

  // ── BEHIND THE SCENES ─────────────────────────────────────────
  { id: 66, category: "Behind the Scenes", difficulty: "Easy", tags: [],
    question: "Who adapted The Office for the United States?",
    answer: "Greg Daniels",
    distractors: ["Ricky Gervais", "Mike Schur", "Mindy Kaling"] },
  { id: 67, category: "Behind the Scenes", difficulty: "Easy", tags: [],
    question: "What was unique about the audition process for The Office?",
    answer: "Actors were interviewed in character rather than reading from scripts",
    distractors: ["Actors had to improvise a full scene with no direction", "Everyone auditioned with the same monologue from the British version", "They used hidden cameras to see how actors behaved off-camera"] },
  { id: 68, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "Who was the first actor to be cast in The Office?",
    answer: "B.J. Novak",
    distractors: ["Steve Carell", "Rainn Wilson", "John Krasinski"] },
  { id: 69, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "Rainn Wilson originally auditioned for which role before being cast as Dwight?",
    answer: "Michael Scott",
    distractors: ["Jim Halpert", "Andy Bernard", "Kevin Malone"] },
  { id: 70, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "What is the name of the real-life podcast hosted by Jenna Fischer and Angela Kinsey about the show?",
    answer: "Office Ladies",
    distractors: ["The Office Deep Dive", "Dunder Mifflin Diaries", "Behind the Paper"] },
  { id: 71, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "John Krasinski and which Office co-star went to the same high school?",
    answer: "B.J. Novak",
    distractors: ["Ed Helms", "Mindy Kaling", "Rainn Wilson"] },
  { id: 72, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "What actor played Andy's brother Walter Jr. in The Office?",
    answer: "Josh Groban",
    distractors: ["Stephen Colbert", "John Mayer", "Ed Sheeran"] },
  { id: 73, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "Who shot the opening credit footage for The Office?",
    answer: "John Krasinski",
    distractors: ["Greg Daniels", "Randall Einhorn", "B.J. Novak"] },
  { id: 74, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "Paul Lieberstein, who played Toby, also served in what other role(s) on the show?",
    answer: "Writer, producer, and director",
    distractors: ["Writer and executive producer only", "Writer and showrunner", "Co-creator and writer"] },
  { id: 75, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "Who directed the season 9 episode 'Work Bus'?",
    answer: "Bryan Cranston",
    distractors: ["Steve Carell", "Jon Favreau", "J.J. Abrams"] },
  { id: 76, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "Because NBC executives weren't told Steve Carell would appear in the finale, who read Michael's lines at the table read?",
    answer: "Creed Bratton",
    distractors: ["B.J. Novak", "Rainn Wilson", "Ed Helms"] },
  { id: 77, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "In season 4, which actress was pregnant in real life and had to hide her belly behind props?",
    answer: "Angela Kinsey",
    distractors: ["Jenna Fischer", "Mindy Kaling", "Phyllis Smith"] },
  { id: 78, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "The casting team originally wanted John Krasinski to audition for which role?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Ryan Howard", "Andy Bernard"] },
  { id: 79, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "The set temperature had to be kept at 64°F — for which reason?",
    answer: "Steve Carell sweats easily",
    distractors: ["The fluorescent lights generated too much heat", "Rainn Wilson's Dwight costume was very heavy", "The camera equipment overheated at higher temperatures"] },
  { id: 80, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "The proposal scene where Jim proposes to Pam was the most expensive shot in the show's history. How much did it cost?",
    answer: "$250,000 (they had to build a replica gas station)",
    distractors: ["$100,000", "$500,000", "$75,000"] },

  // ── RELATIONSHIPS & ROMANCE ───────────────────────────────────
  { id: 81, category: "Relationships & Romance", difficulty: "Easy", tags: [],
    question: "Who was Pam Beesly engaged to before Jim Halpert?",
    answer: "Roy Anderson",
    distractors: ["Danny Cordray", "Alex", "Toby Flenderson"] },
  { id: 82, category: "Relationships & Romance", difficulty: "Easy", tags: [],
    question: "What are the names of Jim and Pam's children?",
    answer: "Cecelia (CeCe) and Phillip",
    distractors: ["Emma and James", "Charlotte and Michael", "Olivia and Ryan"] },
  { id: 83, category: "Relationships & Romance", difficulty: "Easy", tags: [],
    question: "Where does Michael Scott move to start his new life with Holly at the end of the series?",
    answer: "Boulder, Colorado",
    distractors: ["Denver, Colorado", "Austin, Texas", "Portland, Oregon"] },
  { id: 84, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "How many serious girlfriends does Jim have over the course of the show?",
    answer: "Three — Katy, Karen, and Pam",
    distractors: ["Two — Karen and Pam", "Four — Katy, Karen, Pam, and Cathy", "Two — Katy and Pam"] },
  { id: 85, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "Where do Jim and Pam get married?",
    answer: "Niagara Falls (on the ferry boat)",
    distractors: ["Scranton (at the Radisson)", "A church in Pam's hometown", "Schrute Farms"] },
  { id: 86, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "Who was Michael's replacement as Regional Manager before he moved to Colorado?",
    answer: "Deangelo Vickers (played by Will Ferrell)",
    distractors: ["Andy Bernard", "Dwight Schrute", "Robert California"] },
  { id: 87, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "At Phyllis's wedding, what was Michael's nickname for Phyllis in high school?",
    answer: "Easy Rider",
    distractors: ["Big Red", "P-Dawg", "Thunder Thighs"] },
  { id: 88, category: "Relationships & Romance", difficulty: "Hard", tags: [],
    question: "Where did Michael and Jan share their first kiss?",
    answer: "Outside Chili's restaurant",
    distractors: ["In the parking lot at Dunder Mifflin", "At a hotel bar during a business trip", "In Michael's condo"] },
  { id: 89, category: "Relationships & Romance", difficulty: "Hard", tags: [],
    question: "Who did Jan Levinson date after Michael Scott?",
    answer: "Hunter (her former assistant)",
    distractors: ["Clark (from Corporate)", "David Wallace", "A plastic surgeon she met online"] },
  { id: 90, category: "Relationships & Romance", difficulty: "Hard", tags: [],
    question: "What is the name of the exclusive club Pam, Oscar, and Toby form in 'Branch Wars'?",
    answer: "The Finer Things Club",
    distractors: ["The Book Club", "The Philosopher's Circle", "The Culture Committee"] },

  // ── MUSIC & PERFORMANCES ──────────────────────────────────────
  { id: 91, category: "Music & Performances", difficulty: "Easy", tags: [],
    question: "What song does Michael dance down the aisle to at Jim and Pam's wedding?",
    answer: "'Forever' by Chris Brown",
    distractors: ["'Celebration' by Kool & The Gang", "'Here Comes the Sun' by The Beatles", "'Don't Stop Believin'' by Journey"] },
  { id: 92, category: "Music & Performances", difficulty: "Medium", tags: [],
    question: "What is the name of Andy Bernard's college a cappella group?",
    answer: "Here Comes Treble",
    distractors: ["The Do-Re-Migos", "Broccoli Rob and the Broccoli Robs", "The Harmonics"] },
  { id: 93, category: "Music & Performances", difficulty: "Medium", tags: [],
    question: "What Dundie Award does Phyllis win?",
    answer: "Busiest Beaver",
    distractors: ["Hottest in the Office", "Whitest Sneakers", "Longest Engagement"] },
  { id: 94, category: "Music & Performances", difficulty: "Medium", tags: [],
    question: "What song does Michael sing during the 'Fun Run' episode to rally spirits?",
    answer: "'Runaway Train'",
    distractors: ["'Eye of the Tiger'", "'Don't Stop Believin''", "'We Are the Champions'"] },
  { id: 95, category: "Music & Performances", difficulty: "Hard", tags: [],
    question: "What song does Michael sing for his final Dundie performance?",
    answer: "'9,986,000 Minutes'",
    distractors: ["'Goodbye My Lover'", "'Wind Beneath My Wings'", "'Time After Time'"] },
  { id: 96, category: "Music & Performances", difficulty: "Hard", tags: [],
    question: "What song that is NOT by The Police does Scrantonicity perform?",
    answer: "'You Were Meant for Me'",
    distractors: ["'Every Breath You Take'", "'Roxanne'", "'Message in a Bottle'"] },
  { id: 97, category: "Music & Performances", difficulty: "Hard", tags: [],
    question: "During the Benihana Christmas party, what festive song does Michael sing?",
    answer: "'Christmas Time Is Here'",
    distractors: ["'White Christmas'", "'Jingle Bell Rock'", "'Have Yourself a Merry Little Christmas'"] },
  { id: 98, category: "Music & Performances", difficulty: "Hard", tags: [],
    question: "What instrument does Michael play while jamming with Dwight about parenting tips?",
    answer: "Tambourine",
    distractors: ["Guitar", "Keyboard", "Bongos"] },

  // ── LOCATIONS & MISCELLANEOUS ─────────────────────────────────
  { id: 99, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "What city is the Dunder Mifflin Scranton branch located in?",
    answer: "Scranton, Pennsylvania",
    distractors: ["Albany, New York", "Stamford, Connecticut", "Utica, New York"] },
  { id: 100, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "What is Michael Scott's favorite restaurant?",
    answer: "Chili's",
    distractors: ["Hooters", "Benihana", "Sbarro"] },
  { id: 101, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "Where did Michael Scott buy his 'World's Best Boss' mug?",
    answer: "Spencer's",
    distractors: ["Things Remembered", "Hallmark", "Amazon"] },
  { id: 102, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "Where did Jim relocate Dwight's desk in the episode 'The Fight'?",
    answer: "The men's bathroom",
    distractors: ["The parking lot", "The warehouse", "The roof"] },
  { id: 103, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "To which country is Toby Flenderson planning to move after leaving Dunder Mifflin?",
    answer: "Costa Rica",
    distractors: ["Belize", "Panama", "Ecuador"] },
  { id: 104, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "Who is the regional manager of the Stamford branch?",
    answer: "Josh Porter",
    distractors: ["Charles Miner", "David Wallace", "Karen Filippelli"] },
  { id: 105, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "In 'Gay Witch Hunt,' what store does Jim tell Michael and Dwight the Gaydar device comes from?",
    answer: "Sharper Image",
    distractors: ["Brookstone", "SkyMall", "Best Buy"] },
  { id: 106, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What company did Dwight also work for as a secret spy, providing a rival to Dunder Mifflin?",
    answer: "Staples",
    distractors: ["Office Depot", "OfficeMax", "Kinko's"] },
  { id: 107, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "What is the street address of Jim's parents' house in Scranton?",
    answer: "117 Vonburgen Street",
    distractors: ["2530 Slough Avenue", "842 Kellum Court", "1725 Birch Street"] },
  { id: 108, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "What fake client name does Michael use in the episode 'The Client'?",
    answer: "William M. Buttlicker",
    distractors: ["Michael Scotch", "Bill Cosby Butt", "Richard Longbottom"] },
  { id: 109, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "How many Dunder Mifflin birthday parties are there throughout all seasons?",
    answer: "17",
    distractors: ["12", "21", "14"] },
  { id: 110, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "What animal did Dwight put in Holly's car?",
    answer: "A raccoon",
    distractors: ["A possum", "A bat", "A skunk"] },

  // ── CHARACTERS (Vol. 2) ───────────────────────────────────────
  { id: 111, category: "Characters", difficulty: "Easy", tags: [],
    question: "What actress played Meredith Palmer?",
    answer: "Kate Flannery",
    distractors: ["Phyllis Smith", "Angela Kinsey", "Melora Hardin"] },
  { id: 112, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who is the receptionist at Dunder Mifflin at the start of the series?",
    answer: "Pam Beesly",
    distractors: ["Erin Hannon", "Kelly Kapoor", "Meredith Palmer"] },
  { id: 113, category: "Characters", difficulty: "Easy", tags: [],
    question: "What is Pam's job title when she first joins Dunder Mifflin?",
    answer: "Receptionist",
    distractors: ["Office Administrator", "Sales Associate", "Secretary"] },
  { id: 114, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who played Charles Miner, the VP who clashes with Michael in season 5?",
    answer: "Idris Elba",
    distractors: ["James Spader", "Will Ferrell", "Craig Robinson"] },
  { id: 115, category: "Characters", difficulty: "Easy", tags: [],
    question: "What company takes over Dunder Mifflin in season 6?",
    answer: "Sabre",
    distractors: ["Staples", "Prince Family Paper", "Athlead"] },
  { id: 116, category: "Characters", difficulty: "Easy", tags: [],
    question: "What is the group of third-grade students that Michael promised to pay tuition for called?",
    answer: "Scott's Tots",
    distractors: ["Michael's Kids", "The Dunder Scholars", "The Scott Foundation"] },
  { id: 117, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is Stanley's wife's name?",
    answer: "Teri",
    distractors: ["Sandra", "Patricia", "Donna"] },
  { id: 118, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is the name of Stanley's mistress?",
    answer: "Cynthia",
    distractors: ["Lydia", "Melissa", "Donna"] },
  { id: 120, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is the name of Holly's ex-boyfriend who works at Dunder Mifflin Nashua?",
    answer: "A.J.",
    distractors: ["Brad", "Marcus", "Derek"] },
  { id: 121, category: "Characters", difficulty: "Medium", tags: [],
    question: "What are 'New Jim' and 'New Dwight's' real names when they are hired in season 9?",
    answer: "Pete Miller and Clark Green",
    distractors: ["Jason Miller and Brian Green", "Pete Clark and Miller Green", "Matt Miller and David Green"] },
  { id: 122, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is the name of the pediatrician Kelly Kapoor gets engaged to in the finale?",
    answer: "Ravi",
    distractors: ["Sanjay", "Vikram", "Raj"] },
  { id: 123, category: "Characters", difficulty: "Medium", tags: [],
    question: "Which Hollywood actress appeared as the 'Hot Girl' selling handbags in season 1?",
    answer: "Amy Adams",
    distractors: ["Rashida Jones", "Dakota Johnson", "Elizabeth Banks"] },
  { id: 124, category: "Characters", difficulty: "Medium", tags: [],
    question: "Who is the tallest character in The Office?",
    answer: "Gabe Lewis",
    distractors: ["Jim Halpert", "Darryl Philbin", "Roy Anderson"] },
  { id: 125, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is the name of the security guard at the front desk of the Scranton Business Park?",
    answer: "Hank Doyle",
    distractors: ["Frank Didit", "Billy Merchant", "Nate Nickerson"] },
  { id: 126, category: "Characters", difficulty: "Medium", tags: [],
    question: "Who did Robert California choose to be branch manager after taking the CEO role?",
    answer: "Andy Bernard",
    distractors: ["Dwight Schrute", "Jim Halpert", "Darryl Philbin"] },
  { id: 127, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is the name of the hypoallergenic cat Angela buys for $7,000?",
    answer: "Princess Lady",
    distractors: ["Sprinkles", "Bandit", "Mr. Ash"] },
  { id: 128, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is Dwight's karate belt color?",
    answer: "Purple",
    distractors: ["Yellow", "Green", "Orange"] },
  { id: 129, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is the name of Dwight's karate sensei?",
    answer: "Ira",
    distractors: ["Mose", "Gabe", "Nate"] },
  { id: 130, category: "Characters", difficulty: "Hard", tags: [],
    question: "How many of the main cast members share the same first name as their character?",
    answer: "Four — Angela Kinsey, Oscar Nunez, Phyllis Smith, and Creed Bratton",
    distractors: ["Three — Angela Kinsey, Oscar Nunez, and Phyllis Smith", "Five — Angela, Oscar, Phyllis, Creed, and Kevin", "Two — Angela Kinsey and Oscar Nunez"] },
  { id: 131, category: "Characters", difficulty: "Hard", tags: [],
    question: "Why did Kelly Kapoor go to juvenile detention when she was 14?",
    answer: "Her boyfriend dumped her, so she stole his dad's boat",
    distractors: ["She shoplifted designer clothes from a mall", "She started a fire at her school", "She keyed her teacher's car after getting a bad grade"] },
  { id: 132, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is the pet name that Dwight and Angela use to call each other?",
    answer: "Monkey",
    distractors: ["Pumpkin", "Boo Bear", "Snookums"] },
  { id: 133, category: "Characters", difficulty: "Hard", tags: [],
    question: "What is Kevin's magic number he uses to balance his accounts when they don't add up?",
    answer: "Keleven",
    distractors: ["Keleventy", "Kevleven", "Kevinteen"] },

  // ── EPISODES & EVENTS (Vol. 2) ────────────────────────────────
  { id: 134, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What was Ryan heating up in the microwave when he started the fire at the office?",
    answer: "A cheese pita",
    distractors: ["Popcorn", "A Hot Pocket", "Leftover pasta"] },
  { id: 135, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "Which three characters did parkour all over the office in the season 6 cold open?",
    answer: "Michael, Dwight, and Andy",
    distractors: ["Jim, Dwight, and Michael", "Ryan, Kevin, and Dwight", "Andy, Jim, and Kevin"] },
  { id: 136, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What caused Michael to drive his car into a lake?",
    answer: "He followed the GPS directions without question",
    distractors: ["He was distracted by a phone call with Jan", "Dwight grabbed the steering wheel", "He swerved to avoid hitting a deer"] },
  { id: 137, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "Who is the last character to say a line in the entire series?",
    answer: "Pam Beesly",
    distractors: ["Michael Scott", "Dwight Schrute", "Jim Halpert"] },
  { id: 138, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What does Dwight do to the CPR dummy after it is pronounced dead?",
    answer: "He stabs it to harvest its organs",
    distractors: ["He performs a tracheotomy with a pen", "He gives it mouth-to-mouth for 20 minutes", "He throws it out the window"] },
  { id: 139, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "What was the prize the office was playing for in their basketball game against the warehouse in season 1?",
    answer: "Who has to work on Saturday",
    distractors: ["A pizza party", "The loser has to do the winner's work for a week", "Bragging rights and a trophy"] },
  { id: 140, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "Who trips and falls into the lake in a sumo suit during Beach Day?",
    answer: "Andy Bernard",
    distractors: ["Michael Scott", "Dwight Schrute", "Kevin Malone"] },
  { id: 141, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "What song does Kevin sing on the bus on the way to Beach Day?",
    answer: "'The Gambler' by Kenny Rogers",
    distractors: ["'Don't Stop Believin'' by Journey", "'Sweet Home Alabama' by Lynyrd Skynyrd", "'Piano Man' by Billy Joel"] },
  { id: 142, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "Who catches a fish with their bare hands during Beach Day?",
    answer: "Creed Bratton",
    distractors: ["Dwight Schrute", "Meredith Palmer", "Kevin Malone"] },
  { id: 143, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "What holiday do Erin and Andy go on their first date?",
    answer: "St. Patrick's Day",
    distractors: ["Valentine's Day", "Halloween", "Christmas"] },
  { id: 144, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "Who does Meredith flash at the Christmas Party in season 2?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Jim Halpert", "The entire office"] },
  { id: 145, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "Why was Erin first hired at Dunder Mifflin?",
    answer: "Pam left to work at the Michael Scott Paper Company",
    distractors: ["Pam got promoted to sales", "The old receptionist retired", "Michael specifically requested a new receptionist"] },
  { id: 146, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "What is the name of the skit that Michael and Holly perform at the company picnic?",
    answer: "Slumdunder Mifflinaire",
    distractors: ["The Dunder Mifflin Story", "Scranton: The Musical", "Paper Moon"] },
  { id: 147, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "How many times did Andy punch a hole in the wall at the office?",
    answer: "Twice",
    distractors: ["Once", "Three times", "Four times"] },
  { id: 148, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "Who does Oscar have an affair with in the later seasons?",
    answer: "Angela's husband, Senator Robert Lipton",
    distractors: ["Gil, his ex-boyfriend", "A Dunder Mifflin client", "The warehouse manager"] },
  { id: 149, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "What Dundie award does Ryan Howard win at Michael's last Dundies?",
    answer: "Doobie Doobie Pothead Stoner of the Year",
    distractors: ["Hottest in the Office", "Worst Salesman of the Year", "Most Likely to Start a Fire"] },
  { id: 150, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What does Toby break when zip-lining in Costa Rica?",
    answer: "His neck (vertebrae)",
    distractors: ["His leg", "His arm", "His collarbone"] },
  { id: 151, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What does the fax from 'Future Dwight' warn Dwight not to do?",
    answer: "Drink the coffee",
    distractors: ["Open the package from corporate", "Trust Jim Halpert", "Eat the birthday cake"] },
  { id: 152, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What is the acronym Creed writes on the board during a staff meeting when he briefly becomes manager?",
    answer: "BOBODY",
    distractors: ["WUPHF", "DUNDEE", "BIZNUS"] },
  { id: 153, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "After Angela dumps Dwight, what elaborate prank do Jim and Pam play on a severely depressed Dwight?",
    answer: "They pretend the Dunder Mifflin website has become self-aware and wants to outsell him",
    distractors: ["They send him love letters pretending to be from Angela", "They convince him Mose is planning to sell the farm", "They tell him he won a regional sales award"] },
  { id: 154, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What does Michael win a gold medal for at the Office Olympics?",
    answer: "Closing on his condo",
    distractors: ["Winning the yogurt lid flipping contest", "Being the best boss", "Completing his fitness challenge"] },
  { id: 155, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What percentage of Dunder Mifflin's revenue was at risk because of Michael's golden ticket idea?",
    answer: "50%",
    distractors: ["25%", "75%", "100%"] },
  { id: 156, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What rumor does Michael make up about Angela to cover for Stanley's affair?",
    answer: "That she is dating an 81-year-old billionaire who owns a Quizno's franchise",
    distractors: ["That she was a professional cat show judge", "That she once won a beauty pageant in another state", "That she had a secret twin sister"] },
  { id: 157, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "In the 'Stress Relief' episode, what specific thing does Dwight put in the trash can to start the fire?",
    answer: "A lit cigarette",
    distractors: ["A match", "A candle", "A lighter and newspaper"] },
  { id: 158, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What is the date that Ryan and Kelly officially hooked up for the first time?",
    answer: "February 13th",
    distractors: ["February 14th", "March 17th", "December 31st"] },

  // ── QUOTES (Vol. 2) ───────────────────────────────────────────
  { id: 159, category: "Quotes", difficulty: "Easy", tags: [],
    question: "What does Michael say when Pam asks how he describes his management style?",
    answer: "'I'm like a boss, but also a friend. I am a... boss-friend.'",
    distractors: ["'I lead by following, and I follow by leading'", "'I'm not your boss, I'm your best friend who happens to be your boss'", "'I'm a people person who manages people'"] },
  { id: 160, category: "Quotes", difficulty: "Easy", tags: [],
    question: "According to Kevin, what is the trick to making his famous chili?",
    answer: "Undercooking the onions",
    distractors: ["Adding extra cumin", "Using three types of beans", "Slow-cooking it for 24 hours"] },
  { id: 162, category: "Quotes", difficulty: "Medium", tags: [],
    question: "What does Dwight say a beet farmer must have knowledge of?",
    answer: "Bears, beets, and Battlestar Galactica",
    distractors: ["Soil composition, rainfall, and crop rotation", "Farming, self-defense, and survival skills", "Tractor maintenance, irrigation, and accounting"] },
  { id: 163, category: "Quotes", difficulty: "Medium", tags: [],
    question: "What phrase does Michael mangle when he means to say 'the tables have turned'?",
    answer: "'How the turntables...'",
    distractors: ["'How the tables have tabled'", "'Well well well, how the chairs have turned'", "'Oh how the turns have tabled'"] },
  { id: 164, category: "Quotes", difficulty: "Hard", tags: [],
    question: "What is one of the fake interracial phrases Darryl teaches Michael, along with 'Fleece it out'?",
    answer: "'Pippity poppity gimme da zoppidy'",
    distractors: ["'Bippity boppity show me the zoppity'", "'Dinkin' flicka'", "'Zip it up and zip it out'"] },
  { id: 165, category: "Quotes", difficulty: "Hard", tags: [],
    question: "What resort do Michael and Jan stay at in Jamaica?",
    answer: "Sandals",
    distractors: ["Beaches", "Hedonism", "Club Med"] },
  { id: 166, category: "Quotes", difficulty: "Hard", tags: [],
    question: "What does Nellie say to Gabe that becomes a memorable put-down?",
    answer: "'Oh, get out, Skeleton Man!'",
    distractors: ["'Nobody asked you anything, ever'", "'You are a weirdo and everyone hates you'", "'You look like someone starved a butler'"] },
  { id: 167, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Who refers to himself as 'The Lizard King'?",
    answer: "Robert California",
    distractors: ["Dwight Schrute", "Michael Scott", "Creed Bratton"] },
  { id: 168, category: "Quotes", difficulty: "Hard", tags: [],
    question: "What does Stanley say when Dwight releases a bat into the office?",
    answer: "'Goodbye.'",
    distractors: ["'I'm going home.'", "'That is not my problem.'", "'Did I stutter?'"] },

  // ── BEHIND THE SCENES (Vol. 2) ────────────────────────────────
  { id: 169, category: "Behind the Scenes", difficulty: "Easy", tags: [],
    question: "Was the kiss between Oscar and Michael in 'Gay Witch Hunt' scripted?",
    answer: "No — Steve Carell improvised it, kissing Oscar on the mouth when Oscar leaned in for a cheek kiss",
    distractors: ["Yes — it was in the original script from the beginning", "Partially — the hug was scripted but the kiss was improvised", "No — Oscar Nunez suggested it during rehearsal"] },
  { id: 170, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "What song was playing as Jim watched Pam drive away in 'The Dundies' episode?",
    answer: "'Tiny Dancer' by Elton John",
    distractors: ["'Your Song' by Elton John", "'Hallelujah' by Leonard Cohen", "'Yellow' by Coldplay"] },
  { id: 171, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "Which celebrity walked past the camera while Michael was filming himself walking around New York City?",
    answer: "Conan O'Brien",
    distractors: ["Tina Fey", "Jerry Seinfeld", "David Letterman"] },
  { id: 172, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "What book does Dwight read to Jim and Pam during their first stay at Schrute Farms?",
    answer: "Harry Potter and the Deathly Hallows",
    distractors: ["Harry Potter and the Sorcerer's Stone", "The Lord of the Rings", "A Farmer's Almanac"] },
  { id: 173, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "What real-life show did John Krasinski, Mindy Kaling, and Angela Kinsey all intern at before The Office?",
    answer: "Late Night with Conan O'Brien",
    distractors: ["Saturday Night Live", "The Daily Show with Jon Stewart", "Late Show with David Letterman"] },
  { id: 174, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "What prop did Dwight make for a birthday party that caused production to shut down from laughter?",
    answer: "A banner that read 'It is your birthday.'",
    distractors: ["A banner that read 'Congratulations on being born.'", "A banner that read 'You are one year closer to death.'", "A banner with just a photo of his own face"] },
  { id: 175, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "What was The Office's original working title before it launched in the US?",
    answer: "The American Workplace",
    distractors: ["The Paper Company", "Scranton", "The Cubicle"] },
  { id: 176, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "How much did Jim spend on his costume when he dressed up as Dwight?",
    answer: "$11",
    distractors: ["$4", "$25", "$7"] },
  { id: 177, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "What happened to Rainn Wilson on the set of 'Beach Games' that sent a co-star to the hospital?",
    answer: "He accidentally got sand in Leslie David Baker's (Stanley's) eye, resulting in a scratched cornea",
    distractors: ["He tripped and fell into the bonfire, burning his arm", "He stepped on a jellyfish and needed medical attention", "He threw a football too hard and broke a camera"] },
  { id: 178, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "How many cold opens are there across The Office's nine seasons?",
    answer: "188",
    distractors: ["176", "201", "165"] },
  { id: 179, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "What were the five items Jim put in the teapot he gave Pam (not counting the note card)?",
    answer: "A cassette, Jim's high school yearbook photo, a Boggle timer, hot sauce, and a mini golf pencil",
    distractors: ["A letter, Jim's college ID, a dice, Tabasco sauce, and a crayon", "A mixtape, a class photo, a deck of cards, ketchup packets, and a pencil", "A CD, Jim's diploma, a coin, a candy bar, and a bookmark"] },

  // ── RELATIONSHIPS & ROMANCE (Vol. 2) ──────────────────────────
  { id: 180, category: "Relationships & Romance", difficulty: "Easy", tags: [],
    question: "Whose mother does Michael briefly date?",
    answer: "Pam's mother, Helene",
    distractors: ["Jim's mother, Larissa", "Dwight's mother, Hedda", "Angela's mother, Janet"] },
  { id: 181, category: "Relationships & Romance", difficulty: "Easy", tags: [],
    question: "Who does Erin initially think might be her biological mother?",
    answer: "Phyllis",
    distractors: ["Meredith", "Angela", "Jan Levinson"] },
  { id: 182, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "How many women does Michael Scott propose marriage to over the course of the show?",
    answer: "Two — Carol and Holly",
    distractors: ["Three — Carol, Jan, and Holly", "One — Holly", "Two — Jan and Holly"] },
  { id: 183, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "If Pam had married Roy, what would her full married name have been?",
    answer: "Pamela Anderson",
    distractors: ["Pamela Anderson-Beesly", "Patricia Anderson", "Pamela Roy"] },
  { id: 184, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "Why does Pam slap Michael Scott?",
    answer: "He tells everyone that Pam's mom came onto him",
    distractors: ["He made fun of her art at the gallery show", "He called off their lunch plans for the third time", "He fired her without warning"] },
  { id: 185, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "What branch of Dunder Mifflin does Karen Filippelli end up managing after leaving Scranton?",
    answer: "Dunder Mifflin Utica",
    distractors: ["Dunder Mifflin Nashua", "Dunder Mifflin Albany", "Dunder Mifflin Buffalo"] },
  { id: 186, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "Who gets publicly dumped at the Dundies in season 7?",
    answer: "Gabe Lewis (dumped by Erin)",
    distractors: ["Andy Bernard (dumped by Angela)", "Ryan Howard (dumped by Kelly)", "Michael Scott (dumped by Jan)"] },
  { id: 187, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "How did Andy first ask Angela out?",
    answer: "He gave her a cat he trapped outside Vance Refrigeration",
    distractors: ["He serenaded her in the break room with his banjo", "He left roses on her desk every day for a week", "He baked her a cake shaped like a cat"] },
  { id: 188, category: "Relationships & Romance", difficulty: "Hard", tags: [],
    question: "What do Roy and Dwight have in common in the series finale?",
    answer: "Both are seen to have found happiness — Roy with his wife and Dwight with Angela after they finally marry",
    distractors: ["Both moved away from Scranton to start new businesses", "Both proposed to their partners during the documentary screening", "Both were promoted to management positions at their jobs"] },
  { id: 189, category: "Relationships & Romance", difficulty: "Hard", tags: [],
    question: "What heartwarming gift does Stanley give Phyllis in the series finale?",
    answer: "A wooden carving of her with flamingo legs",
    distractors: ["A painting he made of the Dunder Mifflin office", "A book of crossword puzzles he hand-wrote", "A framed photo of them from their first day at the office"] },

  // ── COLD OPENS & RUNNING GAGS ─────────────────────────────────
  { id: 191, category: "Cold Opens & Running Gags", difficulty: "Easy", tags: [],
    question: "What animal does Dwight release into the office by trapping it on someone's head in a garbage bag?",
    answer: "A bat",
    distractors: ["A bird", "A raccoon", "A squirrel"] },
  { id: 192, category: "Cold Opens & Running Gags", difficulty: "Easy", tags: [],
    question: "Which character does the bat bite after Dwight traps it?",
    answer: "Meredith",
    distractors: ["Angela", "Kevin", "Phyllis"] },
  { id: 194, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: [],
    question: "What is the name of the cat Angela throws to Oscar through the ceiling during Dwight's fire drill cold open?",
    answer: "Bandit",
    distractors: ["Sprinkles", "Princess Lady", "Mr. Ash"] },
  { id: 195, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: [],
    question: "Who kicks in the vending machine glass during the fire drill cold open?",
    answer: "Kevin Malone",
    distractors: ["Stanley Hudson", "Dwight Schrute", "Darryl Philbin"] },
  { id: 196, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: [],
    question: "What is Dwight's favorite TV show?",
    answer: "Battlestar Galactica",
    distractors: ["Star Trek", "The X-Files", "Doctor Who"] },
  { id: 197, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: [],
    question: "Besides Jell-O, what other food does Jim put Dwight's stapler in at one point?",
    answer: "A giant meatball",
    distractors: ["A block of ice", "A cake", "A fish tank"] },
  { id: 198, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: [],
    question: "What are the three main events of the Office Olympics?",
    answer: "Flonkerton (box of paper snowshoe racing), Hate Ball, and Who Can Fit the Most M&Ms in Their Mouth",
    distractors: ["Dunderball, Chair Racing, and Paper Airplane Toss", "Box Relay, Trashketball, and Rubber Band Archery", "Stapler Javelin, Office Chair Relay, and Paper Football"] },
  { id: 199, category: "Cold Opens & Running Gags", difficulty: "Hard", tags: [],
    question: "What does Jim do to make Dwight think he can move a coat rack with his mind?",
    answer: "Pam pulls it back and forth using an umbrella hidden under her desk",
    distractors: ["Jim ties fishing line to the coat rack from his desk", "Andy pushes it from behind the wall on cue", "Jim uses a remote-controlled device attached to the base"] },
  { id: 200, category: "Cold Opens & Running Gags", difficulty: "Hard", tags: [],
    question: "After finding half a joint in the parking lot during 'Drug Testing,' who fake-cries during Dwight's investigation?",
    answer: "Jim Halpert",
    distractors: ["Kevin Malone", "Ryan Howard", "Andy Bernard"] },

  // ── LOCATIONS & MISCELLANEOUS (Vol. 2) ────────────────────────
  { id: 201, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "What is the name of the Dunder Mifflin Scranton office building?",
    answer: "Scranton Business Park",
    distractors: ["Scranton Commerce Center", "Dunder Mifflin Plaza", "Lackawanna Office Park"] },
  { id: 202, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "Which branch of Dunder Mifflin does Jim transfer to after season 2?",
    answer: "Dunder Mifflin Stamford",
    distractors: ["Dunder Mifflin Utica", "Dunder Mifflin Nashua", "Dunder Mifflin Albany"] },
  { id: 203, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "What brand of clothing is Michael Scott accidentally wearing when he buys a woman's suit?",
    answer: "MISSterious",
    distractors: ["MISSplaced", "Ms. Taken", "FEMale Fit"] },
  { id: 204, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "What is the name of Pam's friend from art school?",
    answer: "Alex",
    distractors: ["Jamie", "Ben", "Marcus"] },
  { id: 205, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "What actress played Dakota, the accountant who replaced Kevin in the series finale?",
    answer: "Dakota Johnson",
    distractors: ["Aubrey Plaza", "Anna Kendrick", "Emma Stone"] },
  { id: 206, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What does Michael say to Pam about where to put the fax from corporate in the very first episode?",
    answer: "He tells her to put it in a special filing cabinet — which is the garbage can",
    distractors: ["He tells her to fax it back with a funny note", "He says to file it under 'important things I'll never read'", "He tells her to shred it because he doesn't trust corporate"] },
  { id: 207, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "Where does Roy work after leaving Dunder Mifflin?",
    answer: "A vitamin store",
    distractors: ["A gravel company", "A sporting goods store", "A car dealership"] },
  { id: 208, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What celebrity does Darryl say Michael looks like while wearing the women's suit?",
    answer: "Hillary Clinton",
    distractors: ["Ellen DeGeneres", "Martha Stewart", "Oprah Winfrey"] },
  { id: 209, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "Which three coworkers does Jim practice ping pong with before his rematch against Darryl?",
    answer: "Kevin, Meredith, and Dwight",
    distractors: ["Andy, Phyllis, and Stanley", "Oscar, Creed, and Ryan", "Toby, Angela, and Kelly"] },
  { id: 210, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What is the name of the person Michael and Jan meet at Chili's in 'The Client' episode?",
    answer: "Christian",
    distractors: ["Tim", "Brad", "Marcus"] },
  { id: 211, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What costume is Carol wearing when she shows up to Kelly's Diwali party?",
    answer: "A cheerleader costume",
    distractors: ["A nurse costume", "A princess costume", "A witch costume"] },
  { id: 212, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What does Oscar get for Creed in the Secret Santa exchange and why?",
    answer: "A shamrock keychain, because he thinks Creed is Irish",
    distractors: ["A bottle of whiskey, because he thinks Creed is a heavy drinker", "A fishing lure, because he heard Creed likes the outdoors", "A pair of sunglasses, because Creed always wears them"] },
  { id: 213, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What does Michael give Ryan as a Christmas gift, with the price tag still on?",
    answer: "A $400 iPod",
    distractors: ["A $300 leather briefcase", "A $200 watch", "A $500 gift card"] },
  { id: 214, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What song do Michael and Jim sing together after Michael crashes Jim's backyard barbecue?",
    answer: "'Islands in the Stream' by Kenny Rogers and Dolly Parton",
    distractors: ["'Endless Love' by Lionel Richie and Diana Ross", "'Summer Nights' from Grease", "'Don't Go Breaking My Heart' by Elton John and Kiki Dee"] },
  { id: 215, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "What is Toby's daughter's name?",
    answer: "Sasha",
    distractors: ["Emily", "Rachel", "Sophie"] },
  { id: 216, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "What is Pam's middle name?",
    answer: "Morgan",
    distractors: ["Marie", "Anne", "Elizabeth"] },
  { id: 217, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "What fruit does Dwight use to simulate childbirth to help Michael prepare for Jan's baby being born?",
    answer: "A watermelon",
    distractors: ["A pumpkin", "A cantaloupe", "A bowling ball"] },
  { id: 218, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "What does Stanley do to Michael's car after Michael tells Stanley's wife about his affair?",
    answer: "He smashes it with a tire iron",
    distractors: ["He keys it in the parking lot", "He slashes the tires", "He covers it in Post-it notes"] },
  { id: 219, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "What was the name of the Asian actor who played 'Asian Jim' in the prank on Dwight?",
    answer: "Randall Park (his character's name was Steve)",
    distractors: ["Steven Yeun", "John Cho", "Ken Jeong"] },
  { id: 220, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "Which character is arrested and later revealed to have faked their own death in the series finale?",
    answer: "Creed Bratton",
    distractors: ["Kevin Malone", "Meredith Palmer", "Ryan Howard"] },

];

// ── QUOTE REACTIONS ───────────────────────────────────────────────
const QUOTES = {
  correct: [
    { text: "I'm not superstitious, but I am a little stitious — and I knew you'd get that right.", character: "Michael Scott", citation: null },
    { text: "FACT. That answer is correct.", character: "Dwight Schrute", citation: null },
    { text: "That's what she said.", character: "Michael Scott", citation: "S2E2" },
    { text: "I am Beyoncé, always.", character: "Michael Scott", citation: null },
    { text: "You have no idea how high I can fly right now.", character: "Michael Scott", citation: null },
    { text: "Identity theft is not a joke, Jim — but that answer was no joke either.", character: "Dwight Schrute", citation: null },
    { text: "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love my correct answers.", character: "Michael Scott", citation: null },
    { text: "You are a great man. Today, you have shown that.", character: "Michael Scott", citation: null },
    { text: "Bears. Beets. Battlestar Galactica. Correct answers.", character: "Jim Halpert", citation: null },
    { text: "Whenever I'm about to do something, I think — would an idiot do this? You clearly did not do that.", character: "Dwight Schrute", citation: null },
    { text: "You have passed the Schrute test. Few do.", character: "Dwight Schrute", citation: null },
    { text: "As your regional manager, I want to say — well done. I am so proud. Don't make it weird.", character: "Michael Scott", citation: null },
    { text: "I'm not going to say you're a genius. I'm going to say you're a genius.", character: "Michael Scott", citation: null },
    { text: "The people person's paper people salute you.", character: "Michael Scott", citation: null },
    { text: "How the turntables... have turned. In your favor.", character: "Michael Scott", citation: null },
  ],
  incorrect: [
    { text: "Why are you the way that you are?", character: "Michael Scott", citation: "S2E12" },
    { text: "I... DECLARE... BANKRUPTCY... of knowledge.", character: "Michael Scott", citation: null },
    { text: "That is incorrect. FACT.", character: "Dwight Schrute", citation: null },
    { text: "This is the worst thing that has ever happened. In the history of the world.", character: "Michael Scott", citation: null },
    { text: "I'm not mad. I'm just disappointed. Actually I'm both. I'm a little mad.", character: "Michael Scott", citation: null },
    { text: "This is an environment of welcoming, and you have not been welcomed.", character: "Michael Scott", citation: "S1E2" },
    { text: "You have failed this office.", character: "Dwight Schrute", citation: null },
    { text: "How the turntables... have not turned for you today.", character: "Michael Scott", citation: null },
    { text: "Webster's Dictionary defines 'wrong' as — well, that. What you just did.", character: "Michael Scott", citation: null },
    { text: "I knew it. I knew you didn't know that. I said it before and I'll say it again.", character: "Dwight Schrute", citation: null },
    { text: "Oh no. Oh, this is bad. This is very bad.", character: "Kevin Malone", citation: null },
    { text: "That answer is like a Toby answer. And nobody wants that.", character: "Michael Scott", citation: null },
    { text: "You had ONE job. Not literally, you have many jobs. But on this question — one job.", character: "Michael Scott", citation: null },
    { text: "No. No no no no no. Also no.", character: "Michael Scott", citation: null },
    { text: "I'm not angry. I'm just going to need you to go ahead and try that again.", character: "Michael Scott", citation: null },
  ]
};

// ── CATEGORIES & DIFFICULTIES ─────────────────────────────────────
const CATEGORIES = [
  "Characters",
  "Episodes & Events",
  "Quotes",
  "Behind the Scenes",
  "Relationships & Romance",
  "Music & Performances",
  "Locations & Miscellaneous",
  "Cold Opens & Running Gags"
];

const DIFFICULTIES = ["Easy", "Medium", "Hard"];

// ── TAG SUGGESTIONS FOR ADMIN ─────────────────────────────────────
const TAG_SUGGESTIONS = [
  "Michael", "Dwight", "Jim", "Pam", "Ryan", "Kelly", "Angela",
  "Kevin", "Oscar", "Phyllis", "Creed", "Andy", "Toby", "Meredith",
  "Stanley", "Darryl", "Jan", "Holly", "Roy", "Erin", "Gabe",
  "Robert California", "Karen", "Todd Packer", "Ryan", "Nellie",
  "Season 1", "Season 2", "Season 3", "Season 4", "Season 5",
  "Season 6", "Season 7", "Season 8", "Season 9",
  "Pranks", "Romance", "Fire", "Christmas", "Dundies",
  "Cold Open", "Quote", "Food", "Animals", "Finale", "Pilot",
  "Behind the Scenes", "Schrute Farms", "Benihana", "Stamford",
  "Fan Favorite", "Running Gag", "Improvised"
];
