'use strict';
/* ================================================================
   THREAT LEVEL TRIVIA — Static Data
   Questions, quote reactions, categories, tag suggestions
   ================================================================ */

const QUESTIONS = [

  // ── CHARACTERS ────────────────────────────────────────────────
  { id: 1, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who is the Regional Manager of Dunder Mifflin's Scranton branch for most of the series?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Jim Halpert", "Andy Bernard"] },
  { id: 2, category: "Characters", difficulty: "Easy", tags: ["Dwight"],
    question: "What vegetable does Dwight Schrute grow on his farm?",
    answer: "Beets",
    distractors: ["Turnips", "Potatoes", "Radishes"] },
  { id: 3, category: "Characters", difficulty: "Easy", tags: ["Jim"],
    question: "Who is Jim Halpert's primary prank target throughout the series?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Andy Bernard", "Stanley Hudson"] },
  { id: 4, category: "Characters", difficulty: "Easy", tags: ["Dwight"],
    question: "What is Dwight Schrute's official job title?",
    answer: "Assistant to the Regional Manager",
    distractors: ["Assistant Regional Manager", "Sales Associate", "Office Administrator"] },
  { id: 5, category: "Characters", difficulty: "Easy", tags: ["Michael"],
    question: "Who plays Michael Scott in The Office?",
    answer: "Steve Carell",
    distractors: ["Rainn Wilson", "John Krasinski", "Ed Helms"] },
  { id: 6, category: "Characters", difficulty: "Easy", tags: ["Jim"],
    question: "Who plays Jim Halpert?",
    answer: "John Krasinski",
    distractors: ["Steve Carell", "B.J. Novak", "Ed Helms"] },
  { id: 7, category: "Characters", difficulty: "Easy", tags: ["Dwight"],
    question: "Who plays Dwight Schrute?",
    answer: "Rainn Wilson",
    distractors: ["John Krasinski", "Ed Helms", "Craig Robinson"] },
  { id: 8, category: "Characters", difficulty: "Easy", tags: ["Pam"],
    question: "Who plays Pam Beesly?",
    answer: "Jenna Fischer",
    distractors: ["Angela Kinsey", "Mindy Kaling", "Ellie Kemper"] },
  { id: 9, category: "Characters", difficulty: "Easy", tags: ["Michael"],
    question: "Who handles HR at Dunder Mifflin, often to Michael's disdain?",
    answer: "Toby Flenderson",
    distractors: ["Holly Flax", "David Wallace", "Jan Levinson"] },
  { id: 10, category: "Characters", difficulty: "Easy", tags: ["Kevin"],
    question: "What is the name of Kevin Malone's band?",
    answer: "Scrantonicity",
    distractors: ["Here Comes Treble", "The Hunted", "Dunder Mifflinaires"] },
  { id: 11, category: "Characters", difficulty: "Easy", tags: ["Jim", "Andy"],
    question: "What nickname does Andy Bernard give Jim Halpert?",
    answer: "Big Tuna",
    distractors: ["Jimothy", "Halps", "Slim Jim"] },
  { id: 12, category: "Characters", difficulty: "Easy", tags: [],
    question: "What temp-turned-executive started his career at Dunder Mifflin at the bottom?",
    answer: "Ryan Howard",
    distractors: ["Toby Flenderson", "Kelly Kapoor", "Andy Bernard"] },
  { id: 13, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who leads the Party Planning Committee with her love of cats and stern demeanor?",
    answer: "Angela Martin",
    distractors: ["Phyllis Vance", "Pam Beesly", "Kelly Kapoor"] },
  { id: 14, category: "Characters", difficulty: "Medium", tags: ["Dwight"],
    question: "What is the name of Dwight's cousin who lives on the farm with him?",
    answer: "Mose",
    distractors: ["Jeb", "Fannie", "Zeke"] },
  { id: 15, category: "Characters", difficulty: "Medium", tags: ["Michael"],
    question: "What car does Michael Scott drive?",
    answer: "Chrysler Sebring",
    distractors: ["PT Cruiser", "Toyota Camry", "Ford Taurus"] },
  { id: 16, category: "Characters", difficulty: "Medium", tags: ["Angela"],
    question: "What is Angela Martin's middle name?",
    answer: "Noel",
    distractors: ["Marie", "Grace", "Louise"] },
  { id: 17, category: "Characters", difficulty: "Medium", tags: ["Dwight", "Angela"],
    question: "What is the name of Angela's cat that Dwight kills?",
    answer: "Sprinkles",
    distractors: ["Mr. Ash", "Princess Lady", "Bandit"] },
  { id: 18, category: "Characters", difficulty: "Medium", tags: ["Todd Packer"],
    question: "Who portrays the obnoxious traveling salesman Todd Packer?",
    answer: "David Koechner",
    distractors: ["Rob Riggle", "Will Ferrell", "Craig Robinson"] },
  { id: 19, category: "Characters", difficulty: "Medium", tags: ["Michael"],
    question: "What is Michael Scott's embarrassing online dating username?",
    answer: "Littlekidlover",
    distractors: ["Date_Mike", "RegionalManager99", "BestBoss2005"] },
  { id: 20, category: "Characters", difficulty: "Medium", tags: ["Stanley"],
    question: "What is the name of Stanley Hudson's daughter?",
    answer: "Melissa",
    distractors: ["Jessica", "Samantha", "Jasmine"] },
  { id: 21, category: "Characters", difficulty: "Medium", tags: ["Robert California"],
    question: "Who plays Robert California?",
    answer: "James Spader",
    distractors: ["Idris Elba", "Will Ferrell", "Kathy Bates"] },
  { id: 22, category: "Characters", difficulty: "Medium", tags: ["Jim", "Andy"],
    question: "Why does Andy call Jim 'Big Tuna'?",
    answer: "He saw Jim eating a tuna fish sandwich on his first day at the Stamford branch",
    distractors: ["Jim once won a tuna fishing contest", "Jim's favorite restaurant was a seafood place near the office", "Jim wore a tuna-themed shirt on his first day"] },
  { id: 23, category: "Characters", difficulty: "Medium", tags: ["Michael"],
    question: "What kids' show did Michael Scott star in before working at Dunder Mifflin?",
    answer: "Fundle Bundle",
    distractors: ["Puppet Pals", "Sunny Side Up", "Kids' Corner"] },
  { id: 24, category: "Characters", difficulty: "Medium", tags: [],
    question: "What profession is Bob Vance known for?",
    answer: "Refrigeration (owner of Vance Refrigeration)",
    distractors: ["Construction (owner of Vance Construction)", "Plumbing (owner of Vance Plumbing)", "Lumber (owner of Vance Lumber)"] },
  { id: 25, category: "Characters", difficulty: "Medium", tags: ["Jim", "Pam"],
    question: "Who was the first employee in the office to find out about Jim's crush on Pam?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Kevin Malone", "Oscar Martinez"] },
  { id: 26, category: "Characters", difficulty: "Hard", tags: ["Dwight"],
    question: "What is Dwight Schrute's Second Life avatar name?",
    answer: "Dwight Shelford",
    distractors: ["Dwight Schrute II", "RecyclopsX", "Dwight Halperton"] },
  { id: 27, category: "Characters", difficulty: "Hard", tags: ["Michael"],
    question: "What is the name of Michael Scott's ex-girlfriend who was a realtor?",
    answer: "Carol Stills",
    distractors: ["Jan Levinson", "Holly Flax", "Donna Newton"] },
  { id: 28, category: "Characters", difficulty: "Hard", tags: [],
    question: "What waitress's name does the group meet at the Japanese steakhouse (Benihana)?",
    answer: "Cindy",
    distractors: ["Katie", "Nikki", "Jessica"] },
  { id: 29, category: "Characters", difficulty: "Hard", tags: ["Kelly"],
    question: "What is Kelly Kapoor's middle name?",
    answer: "Rajnigandha",
    distractors: ["Priya", "Lakshmi", "Ananya"] },
  { id: 30, category: "Characters", difficulty: "Hard", tags: ["Dwight"],
    question: "What is Dwight's great-grandfather's name?",
    answer: "Dwide Schrute",
    distractors: ["Dwart Schrute", "Dwald Schrute", "Dwight Schrute Sr."] },

  // ── EPISODES & EVENTS ─────────────────────────────────────────
  { id: 31, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What is the name of Dunder Mifflin's annual awards ceremony?",
    answer: "The Dundies",
    distractors: ["The Scranties", "The Dunder Awards", "The Paper Cups"] },
  { id: 32, category: "Episodes & Events", difficulty: "Easy", tags: ["Dwight", "Jim"],
    question: "What does Jim famously put Dwight's stapler in?",
    answer: "Jell-O",
    distractors: ["A vending machine", "A cake", "A block of ice"] },
  { id: 33, category: "Episodes & Events", difficulty: "Easy", tags: ["Michael"],
    question: "How does Michael Scott burn his foot in the episode 'The Injury'?",
    answer: "He steps on his George Foreman grill",
    distractors: ["He spills hot coffee on it", "He kicks a space heater", "He drops a hot panini press on it"] },
  { id: 34, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What is the name of the second episode of the first season?",
    answer: "Diversity Day",
    distractors: ["Health Care", "The Alliance", "Hot Girl"] },
  { id: 35, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What season did Steve Carell leave The Office?",
    answer: "Season 7",
    distractors: ["Season 6", "Season 8", "Season 5"] },
  { id: 36, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "How many total episodes does The Office have?",
    answer: "201",
    distractors: ["188", "212", "196"] },
  { id: 37, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What date did the pilot episode air?",
    answer: "March 24, 2005",
    distractors: ["September 10, 2004", "January 15, 2005", "May 6, 2005"] },
  { id: 38, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "In the 'Diversity Day' episode, whose stand-up routine does Michael imitate?",
    answer: "Chris Rock",
    distractors: ["Dave Chappelle", "Eddie Murphy", "Richard Pryor"] },
  { id: 39, category: "Episodes & Events", difficulty: "Medium", tags: ["Dwight", "Jim"],
    question: "In 'The Injury,' where does Jim pretend to take a concussed Dwight to recover?",
    answer: "Chuck E. Cheese",
    distractors: ["Dave & Buster's", "The hospital", "Hooters"] },
  { id: 40, category: "Episodes & Events", difficulty: "Medium", tags: ["Dwight", "Jim"],
    question: "In the 'Product Recall' episode, who does Jim dress up as to prank Dwight?",
    answer: "Dwight (himself)",
    distractors: ["Michael Scott", "Stanley Hudson", "Andy Bernard"] },
  { id: 41, category: "Episodes & Events", difficulty: "Medium", tags: ["Kevin"],
    question: "In the 'Christmas Party' episode, who does Kevin get for Secret Santa?",
    answer: "Himself",
    distractors: ["Angela", "Michael", "Oscar"] },
  { id: 42, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael", "Meredith"],
    question: "In which episode does Michael Scott accidentally hit Meredith with his car?",
    answer: "Fun Run",
    distractors: ["Safety Training", "The Injury", "Beach Games"] },
  { id: 43, category: "Episodes & Events", difficulty: "Medium", tags: ["Andy"],
    question: "In what season is Andy Bernard first introduced?",
    answer: "Season 3",
    distractors: ["Season 2", "Season 4", "Season 5"] },
  { id: 44, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "In 'The Coup,' what high school movie does Michael watch for Movie Mondays?",
    answer: "Varsity Blues",
    distractors: ["Armageddon", "Entourage", "The Breakfast Club"] },
  { id: 45, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael", "Pam"],
    question: "In which episode does Michael Scott pretend to fire Pam as a prank?",
    answer: "The Pilot",
    distractors: ["Diversity Day", "Hot Girl", "The Alliance"] },
  { id: 46, category: "Episodes & Events", difficulty: "Medium", tags: ["Dwight"],
    question: "In 'The Job,' what color does Dwight paint his office when he becomes interim Regional Manager?",
    answer: "Black",
    distractors: ["Red", "Dark Brown", "Navy Blue"] },
  { id: 47, category: "Episodes & Events", difficulty: "Medium", tags: ["Dwight", "Stanley"],
    question: "What is the name of the episode where Dwight stages a fire drill and causes Stanley to have a heart attack?",
    answer: "Stress Relief",
    distractors: ["The Fire", "Safety Training", "Fun Run"] },
  { id: 48, category: "Episodes & Events", difficulty: "Medium", tags: ["Jim", "Pam"],
    question: "In what episode does Jim propose to Pam?",
    answer: "Weight Loss",
    distractors: ["Goodbye, Toby", "Niagara", "Crime Aid"] },
  { id: 49, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "What was the event called when Michael took everyone on a boat cruise in season two?",
    answer: "Booze Cruise",
    distractors: ["Office Cruise", "Party Boat", "Dunder Cruise"] },
  { id: 50, category: "Episodes & Events", difficulty: "Hard", tags: ["Michael", "Dwight", "Stanley"],
    question: "What does Stanley secretly tell his wife to buy over the phone after Michael announces $1,000 raises in 'Dwight's Speech'?",
    answer: "Wallpaper",
    distractors: ["A new couch", "Curtains", "A flat screen TV"] },
  { id: 51, category: "Episodes & Events", difficulty: "Hard", tags: ["Dwight", "Jim"],
    question: "In 'Conflict Resolution,' what two things does Jim label on Dwight's fake security badge?",
    answer: "'Security risk' and 'Fart' as his middle name",
    distractors: ["'Extremely dangerous' and 'Karate expert'", "'Authorized idiot' and 'Beet juice' as blood type", "'Top secret clearance' and 'Weapons grade stupidity'"] },
  { id: 52, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "In 'The Merger,' which Stamford branch employee is the first to quit?",
    answer: "Tony",
    distractors: ["Karen Filippelli", "Hannah", "Martin"] },
  { id: 53, category: "Episodes & Events", difficulty: "Hard", tags: ["Kevin"],
    question: "In 'Office Olympics,' what scent does Kevin claim the Eternal Burning of Competition candle smells like?",
    answer: "Cookies",
    distractors: ["Vanilla", "Cinnamon", "Burnt popcorn"] },
  { id: 54, category: "Episodes & Events", difficulty: "Hard", tags: ["Pam", "Roy"],
    question: "While Pam reviews last year's Dundie Awards video, what is Roy eating?",
    answer: "Chicken Crispers",
    distractors: ["Hot wings", "Pizza", "Nachos"] },
  { id: 55, category: "Episodes & Events", difficulty: "Hard", tags: ["Jim"],
    question: "In 'Drug Testing,' who does Jim catch overhearing him do an impression while coming out of the bathroom?",
    answer: "Stanley",
    distractors: ["Dwight", "Ryan", "Toby"] },

  // ── QUOTES ────────────────────────────────────────────────────
  { id: 56, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Which character is known for saying 'That's what she said'?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Jim Halpert", "Kevin Malone"] },
  { id: 57, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Which character says 'Bears, beets, Battlestar Galactica'?",
    answer: "Jim Halpert (impersonating Dwight)",
    distractors: ["Dwight Schrute", "Michael Scott", "Andy Bernard"] },
  { id: 58, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Who says: 'I am ready to face any challenges that might be foolish enough to face me'?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Andy Bernard", "Robert California"] },
  { id: 59, category: "Quotes", difficulty: "Medium", tags: ["Michael"],
    question: "Michael Scott says he is 'not superstitious, but...' How does he finish that sentence?",
    answer: "'I am a little stitious'",
    distractors: ["'I am a little nervous'", "'I am pretty cautious'", "'I believe in coincidences'"] },
  { id: 60, category: "Quotes", difficulty: "Medium", tags: ["Michael"],
    question: "Who teaches Michael the phrases 'Fleece it out' and 'Going mach five' as fake slang?",
    answer: "Darryl Philbin",
    distractors: ["Stanley Hudson", "Ryan Howard", "Kevin Malone"] },
  { id: 61, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Which character says: 'Reject a woman and she will never let it go. One of the many defects of their kind. Also weak arms.'?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Robert California", "Ryan Howard"] },
  { id: 62, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Which character says: 'I know that patience and loyalty are good and virtuous traits, but sometimes I just think you need to grow a pair.'?",
    answer: "Angela Martin",
    distractors: ["Jan Levinson", "Kelly Kapoor", "Phyllis Vance"] },
  { id: 63, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Which character says: 'I never really thought about death until Princess Diana died. That was the saddest funeral ever, that and my sister's.'?",
    answer: "Kelly Kapoor",
    distractors: ["Michael Scott", "Ryan Howard", "Meredith Palmer"] },
  { id: 64, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Which character says 'You miss 100% of the shots you don’t take - Wayne Gretzky' and is credited as having said it?",
    answer: "Michael Scott (he attributes it to Wayne Gretzky)",
    distractors: ["Dwight Schrute", "Jim Halpert", "Andy Bernard"] },
  { id: 65, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Which character says: 'In the '60s I made love to many, many women, often outdoors in the mud and rain... and it's possible a man slipped in.'?",
    answer: "Creed Bratton",
    distractors: ["Michael Scott", "Meredith Palmer", "Robert California"] },

  // ── BEHIND THE SCENES ─────────────────────────────────────────
  { id: 66, category: "Behind the Scenes", difficulty: "Easy", tags: [],
    question: "Who adapted The Office for the United States?",
    answer: "Greg Daniels",
    distractors: ["Ricky Gervais", "Mike Schur", "Mindy Kaling"] },
  { id: 67, category: "Behind the Scenes", difficulty: "Easy", tags: [],
    question: "What was unique about the audition process for The Office?",
    answer: "Actors were interviewed in character rather than reading from scripts",
    distractors: ["Actors had to improvise a full scene with no direction", "Everyone auditioned with the same monologue from the British version", "They used hidden cameras to see how actors behaved off-camera"] },
  { id: 68, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "Who was the first actor to be cast in The Office?",
    answer: "B.J. Novak",
    distractors: ["Steve Carell", "Rainn Wilson", "John Krasinski"] },
  { id: 69, category: "Behind the Scenes", difficulty: "Medium", tags: ["Dwight"],
    question: "Rainn Wilson originally auditioned for which role before being cast as Dwight?",
    answer: "Michael Scott",
    distractors: ["Jim Halpert", "Andy Bernard", "Kevin Malone"] },
  { id: 70, category: "Behind the Scenes", difficulty: "Medium", tags: ["Angela"],
    question: "What is the name of the real-life podcast hosted by Jenna Fischer and Angela Kinsey about the show?",
    answer: "Office Ladies",
    distractors: ["The Office Deep Dive", "Dunder Mifflin Diaries", "Behind the Paper"] },
  { id: 71, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "John Krasinski and which Office co-star went to the same high school?",
    answer: "B.J. Novak",
    distractors: ["Ed Helms", "Mindy Kaling", "Rainn Wilson"] },
  { id: 72, category: "Behind the Scenes", difficulty: "Medium", tags: ["Andy"],
    question: "What actor played Andy's brother Walter Jr. in The Office?",
    answer: "Josh Groban",
    distractors: ["Stephen Colbert", "John Mayer", "Ed Sheeran"] },
  { id: 73, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "Who shot the opening credit footage for The Office?",
    answer: "John Krasinski",
    distractors: ["Greg Daniels", "Randall Einhorn", "B.J. Novak"] },
  { id: 74, category: "Behind the Scenes", difficulty: "Medium", tags: ["Toby"],
    question: "Paul Lieberstein, who played Toby, also served in what other role(s) on the show?",
    answer: "Writer, producer, and director",
    distractors: ["Writer and executive producer only", "Writer and showrunner", "Co-creator and writer"] },
  { id: 75, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "Who directed the season 9 episode 'Work Bus'?",
    answer: "Bryan Cranston",
    distractors: ["Steve Carell", "Jon Favreau", "J.J. Abrams"] },
  { id: 76, category: "Behind the Scenes", difficulty: "Hard", tags: ["Michael"],
    question: "Because NBC executives weren't told Steve Carell would appear in the finale, who read Michael's lines at the table read?",
    answer: "Creed Bratton",
    distractors: ["B.J. Novak", "Rainn Wilson", "Ed Helms"] },
  { id: 77, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "In season 4, which actress was pregnant in real life and had to hide her belly behind props?",
    answer: "Angela Kinsey",
    distractors: ["Jenna Fischer", "Mindy Kaling", "Phyllis Smith"] },
  { id: 78, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "The casting team originally wanted John Krasinski to audition for which role?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Ryan Howard", "Andy Bernard"] },
  { id: 79, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "The set temperature had to be kept at 64°F - for which reason?",
    answer: "Steve Carell sweats easily",
    distractors: ["The fluorescent lights generated too much heat", "Rainn Wilson's Dwight costume was very heavy", "The camera equipment overheated at higher temperatures"] },
  { id: 80, category: "Behind the Scenes", difficulty: "Hard", tags: ["Jim", "Pam"],
    question: "The proposal scene where Jim proposes to Pam was the most expensive shot in the show's history. How much did it cost?",
    answer: "$250,000 (they had to build a replica gas station)",
    distractors: ["$100,000", "$500,000", "$75,000"] },

  // ── RELATIONSHIPS & ROMANCE ───────────────────────────────────
  { id: 81, category: "Relationships & Romance", difficulty: "Easy", tags: ["Jim", "Pam"],
    question: "Who was Pam Beesly engaged to before Jim Halpert?",
    answer: "Roy Anderson",
    distractors: ["Danny Cordray", "Alex", "Toby Flenderson"] },
  { id: 82, category: "Relationships & Romance", difficulty: "Easy", tags: ["Jim", "Pam"],
    question: "What are the names of Jim and Pam's children?",
    answer: "Cecelia (CeCe) and Phillip",
    distractors: ["Emma and James", "Charlotte and Michael", "Olivia and Ryan"] },
  { id: 83, category: "Relationships & Romance", difficulty: "Easy", tags: ["Michael", "Holly"],
    question: "Where does Michael Scott move to start his new life with Holly at the end of the series?",
    answer: "Boulder, Colorado",
    distractors: ["Denver, Colorado", "Austin, Texas", "Portland, Oregon"] },
  { id: 84, category: "Relationships & Romance", difficulty: "Medium", tags: ["Jim"],
    question: "How many serious girlfriends does Jim have over the course of the show?",
    answer: "Three: Katy, Karen, and Pam",
    distractors: ["Two: Karen and Pam", "Four: Katy, Karen, Pam, and Cathy", "Two: Katy and Pam"] },
  { id: 85, category: "Relationships & Romance", difficulty: "Medium", tags: ["Jim", "Pam"],
    question: "Where do Jim and Pam get married?",
    answer: "Niagara Falls (on the ferry boat)",
    distractors: ["Scranton (at the Radisson)", "A church in Pam's hometown", "Schrute Farms"] },
  { id: 86, category: "Relationships & Romance", difficulty: "Medium", tags: ["Michael"],
    question: "Who was Michael's replacement as Regional Manager before he moved to Colorado?",
    answer: "Deangelo Vickers (played by Will Ferrell)",
    distractors: ["Andy Bernard", "Dwight Schrute", "Robert California"] },
  { id: 87, category: "Relationships & Romance", difficulty: "Medium", tags: ["Michael", "Phyllis"],
    question: "At Phyllis's wedding, what was Michael's nickname for Phyllis in high school?",
    answer: "Easy Rider",
    distractors: ["Big Red", "P-Dawg", "Thunder Thighs"] },
  { id: 88, category: "Relationships & Romance", difficulty: "Hard", tags: ["Michael", "Jan"],
    question: "Where did Michael and Jan share their first kiss?",
    answer: "Outside Chili's restaurant",
    distractors: ["In the parking lot at Dunder Mifflin", "At a hotel bar during a business trip", "In Michael's condo"] },
  { id: 89, category: "Relationships & Romance", difficulty: "Hard", tags: ["Michael", "Jan"],
    question: "Who did Jan Levinson date after Michael Scott?",
    answer: "Hunter (her former assistant)",
    distractors: ["Clark (from Corporate)", "David Wallace", "A plastic surgeon she met online"] },
  { id: 90, category: "Relationships & Romance", difficulty: "Hard", tags: ["Pam", "Oscar", "Toby"],
    question: "What is the name of the exclusive club Pam, Oscar, and Toby form in 'Branch Wars'?",
    answer: "The Finer Things Club",
    distractors: ["The Book Club", "The Philosopher's Circle", "The Culture Committee"] },

  // ── MUSIC & PERFORMANCES ──────────────────────────────────────
  { id: 91, category: "Music & Performances", difficulty: "Easy", tags: ["Michael", "Jim", "Pam"],
    question: "What song does Michael dance down the aisle to at Jim and Pam's wedding?",
    answer: "'Forever' by Chris Brown",
    distractors: ["'Celebration' by Kool & The Gang", "'Here Comes the Sun' by The Beatles", "'Don't Stop Believin'' by Journey"] },
  { id: 92, category: "Music & Performances", difficulty: "Medium", tags: ["Andy"],
    question: "What is the name of Andy Bernard's college a cappella group?",
    answer: "Here Comes Treble",
    distractors: ["The Do-Re-Migos", "Broccoli Rob and the Broccoli Robs", "The Harmonics"] },
  { id: 93, category: "Music & Performances", difficulty: "Medium", tags: ["Phyllis"],
    question: "What Dundie Award does Phyllis win?",
    answer: "Busiest Beaver",
    distractors: ["Hottest in the Office", "Whitest Sneakers", "Longest Engagement"] },
  { id: 94, category: "Music & Performances", difficulty: "Medium", tags: ["Michael"],
    question: "What song does Michael sing during the 'Fun Run' episode to rally spirits?",
    answer: "'Runaway Train'",
    distractors: ["'Eye of the Tiger'", "'Don't Stop Believin''", "'We Are the Champions'"] },
  { id: 95, category: "Music & Performances", difficulty: "Hard", tags: ["Michael"],
    question: "What song does Michael sing for his final Dundie performance?",
    answer: "'9,986,000 Minutes'",
    distractors: ["'Goodbye My Lover'", "'Wind Beneath My Wings'", "'Time After Time'"] },
  { id: 96, category: "Music & Performances", difficulty: "Hard", tags: [],
    question: "What song that is NOT by The Police does Scrantonicity perform?",
    answer: "'You Were Meant for Me'",
    distractors: ["'Every Breath You Take'", "'Roxanne'", "'Message in a Bottle'"] },
  { id: 97, category: "Music & Performances", difficulty: "Hard", tags: ["Michael"],
    question: "During the Benihana Christmas party, what festive song does Michael sing?",
    answer: "'Christmas Time Is Here'",
    distractors: ["'White Christmas'", "'Jingle Bell Rock'", "'Have Yourself a Merry Little Christmas'"] },
  { id: 98, category: "Music & Performances", difficulty: "Hard", tags: ["Michael", "Dwight"],
    question: "What instrument does Michael play while jamming with Dwight about parenting tips?",
    answer: "Tambourine",
    distractors: ["Guitar", "Keyboard", "Bongos"] },

  // ── LOCATIONS & MISCELLANEOUS ─────────────────────────────────
  { id: 99, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "What city is the Dunder Mifflin Scranton branch located in?",
    answer: "Scranton, Pennsylvania",
    distractors: ["Albany, New York", "Stamford, Connecticut", "Utica, New York"] },
  { id: 100, category: "Locations & Miscellaneous", difficulty: "Easy", tags: ["Michael"],
    question: "What is Michael Scott's favorite restaurant?",
    answer: "Chili's",
    distractors: ["Hooters", "Benihana", "Sbarro"] },
  { id: 101, category: "Locations & Miscellaneous", difficulty: "Easy", tags: ["Michael"],
    question: "Where did Michael Scott buy his 'World's Best Boss' mug?",
    answer: "Spencer's",
    distractors: ["Things Remembered", "Hallmark", "Amazon"] },
  { id: 102, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Dwight", "Jim"],
    question: "Where did Jim relocate Dwight's desk in the episode 'The Fight'?",
    answer: "The men's bathroom",
    distractors: ["The parking lot", "The warehouse", "The roof"] },
  { id: 103, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Toby"],
    question: "To which country is Toby Flenderson planning to move after leaving Dunder Mifflin?",
    answer: "Costa Rica",
    distractors: ["Belize", "Panama", "Ecuador"] },
  { id: 104, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "Who is the regional manager of the Stamford branch?",
    answer: "Josh Porter",
    distractors: ["Charles Miner", "David Wallace", "Karen Filippelli"] },
  { id: 105, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Michael", "Dwight", "Jim"],
    question: "In 'Gay Witch Hunt,' what store does Jim tell Michael and Dwight the Gaydar device comes from?",
    answer: "Sharper Image",
    distractors: ["Brookstone", "SkyMall", "Best Buy"] },
  { id: 106, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Dwight"],
    question: "What company did Dwight also work for as a secret spy, providing a rival to Dunder Mifflin?",
    answer: "Staples",
    distractors: ["Office Depot", "OfficeMax", "Kinko's"] },
  { id: 107, category: "Locations & Miscellaneous", difficulty: "Hard", tags: ["Jim"],
    question: "What is the street address of Jim's parents' house in Scranton?",
    answer: "117 Vonburgen Street",
    distractors: ["2530 Slough Avenue", "842 Kellum Court", "1725 Birch Street"] },
  { id: 108, category: "Locations & Miscellaneous", difficulty: "Hard", tags: ["Michael"],
    question: "What fake client name does Michael use in the episode 'The Client'?",
    answer: "William M. Buttlicker",
    distractors: ["Michael Scotch", "Bill Cosby Butt", "Richard Longbottom"] },
  { id: 109, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "How many Dunder Mifflin birthday parties are there throughout all seasons?",
    answer: "17",
    distractors: ["12", "21", "14"] },
  { id: 110, category: "Locations & Miscellaneous", difficulty: "Hard", tags: ["Dwight", "Holly"],
    question: "What animal did Dwight put in Holly's car?",
    answer: "A raccoon",
    distractors: ["A possum", "A bat", "A skunk"] },

  // ── CHARACTERS (Vol. 2) ───────────────────────────────────────
  { id: 111, category: "Characters", difficulty: "Easy", tags: ["Meredith"],
    question: "What actress played Meredith Palmer?",
    answer: "Kate Flannery",
    distractors: ["Phyllis Smith", "Angela Kinsey", "Melora Hardin"] },
  { id: 112, category: "Characters", difficulty: "Easy", tags: [],
    question: "Who is the receptionist at Dunder Mifflin at the start of the series?",
    answer: "Pam Beesly",
    distractors: ["Erin Hannon", "Kelly Kapoor", "Meredith Palmer"] },
  { id: 113, category: "Characters", difficulty: "Easy", tags: ["Pam"],
    question: "What is Pam's job title when she first joins Dunder Mifflin?",
    answer: "Receptionist",
    distractors: ["Office Administrator", "Sales Associate", "Secretary"] },
  { id: 114, category: "Characters", difficulty: "Easy", tags: ["Michael"],
    question: "Who played Charles Miner, the VP who clashes with Michael in season 5?",
    answer: "Idris Elba",
    distractors: ["James Spader", "Will Ferrell", "Craig Robinson"] },
  { id: 115, category: "Characters", difficulty: "Easy", tags: [],
    question: "What company takes over Dunder Mifflin in season 6?",
    answer: "Sabre",
    distractors: ["Staples", "Prince Family Paper", "Athlead"] },
  { id: 116, category: "Characters", difficulty: "Easy", tags: ["Michael"],
    question: "What is the group of third-grade students that Michael promised to pay tuition for called?",
    answer: "Scott's Tots",
    distractors: ["Michael's Kids", "The Dunder Scholars", "The Scott Foundation"] },
  { id: 117, category: "Characters", difficulty: "Medium", tags: ["Stanley"],
    question: "What is Stanley's wife's name?",
    answer: "Teri",
    distractors: ["Sandra", "Patricia", "Donna"] },
  { id: 118, category: "Characters", difficulty: "Medium", tags: ["Stanley"],
    question: "What is the name of Stanley's mistress?",
    answer: "Cynthia",
    distractors: ["Lydia", "Melissa", "Donna"] },
  { id: 120, category: "Characters", difficulty: "Medium", tags: ["Holly"],
    question: "What is the name of Holly's ex-boyfriend who works at Dunder Mifflin Nashua?",
    answer: "A.J.",
    distractors: ["Brad", "Marcus", "Derek"] },
  { id: 121, category: "Characters", difficulty: "Medium", tags: ["Dwight", "Jim"],
    question: "What are 'New Jim' and 'New Dwight's' real names when they are hired in season 9?",
    answer: "Pete Miller and Clark Green",
    distractors: ["Jason Miller and Brian Green", "Pete Clark and Miller Green", "Matt Miller and David Green"] },
  { id: 122, category: "Characters", difficulty: "Medium", tags: ["Kelly"],
    question: "What is the name of the pediatrician Kelly Kapoor gets engaged to in the finale?",
    answer: "Ravi",
    distractors: ["Sanjay", "Vikram", "Raj"] },
  { id: 123, category: "Characters", difficulty: "Medium", tags: [],
    question: "Which Hollywood actress appeared as the 'Hot Girl' selling handbags in season 1?",
    answer: "Amy Adams",
    distractors: ["Rashida Jones", "Dakota Johnson", "Elizabeth Banks"] },
  { id: 124, category: "Characters", difficulty: "Medium", tags: [],
    question: "Who is the tallest character in The Office?",
    answer: "Gabe Lewis",
    distractors: ["Jim Halpert", "Darryl Philbin", "Roy Anderson"] },
  { id: 125, category: "Characters", difficulty: "Medium", tags: [],
    question: "What is the name of the security guard at the front desk of the Scranton Business Park?",
    answer: "Hank Doyle",
    distractors: ["Frank Didit", "Billy Merchant", "Nate Nickerson"] },
  { id: 126, category: "Characters", difficulty: "Medium", tags: ["Robert California"],
    question: "Who did Robert California choose to be branch manager after taking the CEO role?",
    answer: "Andy Bernard",
    distractors: ["Dwight Schrute", "Jim Halpert", "Darryl Philbin"] },
  { id: 127, category: "Characters", difficulty: "Hard", tags: ["Angela"],
    question: "What is the name of the hypoallergenic cat Angela buys for $7,000?",
    answer: "Princess Lady",
    distractors: ["Sprinkles", "Bandit", "Mr. Ash"] },
  { id: 128, category: "Characters", difficulty: "Hard", tags: ["Dwight"],
    question: "What is Dwight's karate belt color?",
    answer: "Purple",
    distractors: ["Yellow", "Green", "Orange"] },
  { id: 129, category: "Characters", difficulty: "Hard", tags: ["Dwight"],
    question: "What is the name of Dwight's karate sensei?",
    answer: "Ira",
    distractors: ["Mose", "Gabe", "Nate"] },
  { id: 130, category: "Characters", difficulty: "Hard", tags: [],
    question: "How many of the main cast members share the same first name as their character?",
    answer: "Four: Angela Kinsey, Oscar Nunez, Phyllis Smith, and Creed Bratton",
    distractors: ["Three: Angela Kinsey, Oscar Nunez, and Phyllis Smith", "Five: Angela, Oscar, Phyllis, Creed, and Kevin", "Two: Angela Kinsey and Oscar Nunez"] },
  { id: 131, category: "Characters", difficulty: "Hard", tags: ["Kelly"],
    question: "Why did Kelly Kapoor go to juvenile detention when she was 14?",
    answer: "Her boyfriend dumped her, so she stole his dad's boat",
    distractors: ["She shoplifted designer clothes from a mall", "She started a fire at her school", "She keyed her teacher's car after getting a bad grade"] },
  { id: 132, category: "Characters", difficulty: "Hard", tags: ["Dwight", "Angela"],
    question: "What is the pet name that Dwight and Angela use to call each other?",
    answer: "Monkey",
    distractors: ["Pumpkin", "Boo Bear", "Snookums"] },
  { id: 133, category: "Characters", difficulty: "Hard", tags: ["Kevin"],
    question: "What is Kevin's magic number he uses to balance his accounts when they don't add up?",
    answer: "Keleven",
    distractors: ["Keleventy", "Kevleven", "Kevinteen"] },

  // ── EPISODES & EVENTS (Vol. 2) ────────────────────────────────
  { id: 134, category: "Episodes & Events", difficulty: "Easy", tags: ["Ryan"],
    question: "What was Ryan heating up in the microwave when he started the fire at the office?",
    answer: "A cheese pita",
    distractors: ["Popcorn", "A Hot Pocket", "Leftover pasta"] },
  { id: 135, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "Which three characters did parkour all over the office in the season 6 cold open?",
    answer: "Michael, Dwight, and Andy",
    distractors: ["Jim, Dwight, and Michael", "Ryan, Kevin, and Dwight", "Andy, Jim, and Kevin"] },
  { id: 136, category: "Episodes & Events", difficulty: "Easy", tags: ["Michael"],
    question: "What caused Michael to drive his car into a lake?",
    answer: "He followed the GPS directions without question",
    distractors: ["He was distracted by a phone call with Jan", "Dwight grabbed the steering wheel", "He swerved to avoid hitting a deer"] },
  { id: 137, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "Who is the last character to say a line in the entire series?",
    answer: "Pam Beesly",
    distractors: ["Michael Scott", "Dwight Schrute", "Jim Halpert"] },
  { id: 138, category: "Episodes & Events", difficulty: "Easy", tags: ["Dwight"],
    question: "What does Dwight do to the CPR dummy after it is pronounced dead?",
    answer: "He stabs it to harvest its organs",
    distractors: ["He performs a tracheotomy with a pen", "He gives it mouth-to-mouth for 20 minutes", "He throws it out the window"] },
  { id: 139, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "What was the prize the office was playing for in their basketball game against the warehouse in season 1?",
    answer: "Who has to work on Saturday",
    distractors: ["A pizza party", "The loser has to do the winner's work for a week", "Bragging rights and a trophy"] },
  { id: 140, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "Who trips and falls into the lake in a sumo suit during Beach Day?",
    answer: "Andy Bernard",
    distractors: ["Michael Scott", "Dwight Schrute", "Kevin Malone"] },
  { id: 141, category: "Episodes & Events", difficulty: "Medium", tags: ["Kevin"],
    question: "What song does Kevin sing on the bus on the way to Beach Day?",
    answer: "'The Gambler' by Kenny Rogers",
    distractors: ["'Don't Stop Believin'' by Journey", "'Sweet Home Alabama' by Lynyrd Skynyrd", "'Piano Man' by Billy Joel"] },
  { id: 142, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "Who catches a fish with their bare hands during Beach Day?",
    answer: "Creed Bratton",
    distractors: ["Dwight Schrute", "Meredith Palmer", "Kevin Malone"] },
  { id: 143, category: "Episodes & Events", difficulty: "Medium", tags: ["Andy", "Erin"],
    question: "What holiday do Erin and Andy go on their first date?",
    answer: "St. Patrick's Day",
    distractors: ["Valentine's Day", "Halloween", "Christmas"] },
  { id: 144, category: "Episodes & Events", difficulty: "Medium", tags: ["Meredith"],
    question: "Who does Meredith flash at the Christmas Party in season 2?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Jim Halpert", "The entire office"] },
  { id: 145, category: "Episodes & Events", difficulty: "Medium", tags: ["Erin"],
    question: "Why was Erin first hired at Dunder Mifflin?",
    answer: "Pam left to work at the Michael Scott Paper Company",
    distractors: ["Pam got promoted to sales", "The old receptionist retired", "Michael specifically requested a new receptionist"] },
  { id: 146, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael", "Holly"],
    question: "What is the name of the skit that Michael and Holly perform at the company picnic?",
    answer: "Slumdunder Mifflinaire",
    distractors: ["The Dunder Mifflin Story", "Scranton: The Musical", "Paper Moon"] },
  { id: 147, category: "Episodes & Events", difficulty: "Medium", tags: ["Andy"],
    question: "How many times did Andy punch a hole in the wall at the office?",
    answer: "Twice",
    distractors: ["Once", "Three times", "Four times"] },
  { id: 148, category: "Episodes & Events", difficulty: "Medium", tags: ["Oscar"],
    question: "Who does Oscar have an affair with in the later seasons?",
    answer: "Angela's husband, Senator Robert Lipton",
    distractors: ["Gil, his ex-boyfriend", "A Dunder Mifflin client", "The warehouse manager"] },
  { id: 149, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael", "Ryan"],
    question: "What Dundie award does Ryan Howard win at Michael's last Dundies?",
    answer: "Doobie Doobie Pothead Stoner of the Year",
    distractors: ["Hottest in the Office", "Worst Salesman of the Year", "Most Likely to Start a Fire"] },
  { id: 150, category: "Episodes & Events", difficulty: "Hard", tags: ["Toby"],
    question: "What does Toby break when zip-lining in Costa Rica?",
    answer: "His neck (vertebrae)",
    distractors: ["His leg", "His arm", "His collarbone"] },
  { id: 151, category: "Episodes & Events", difficulty: "Hard", tags: ["Dwight"],
    question: "What does the fax from 'Future Dwight' warn Dwight not to do?",
    answer: "Drink the coffee",
    distractors: ["Open the package from corporate", "Trust Jim Halpert", "Eat the birthday cake"] },
  { id: 152, category: "Episodes & Events", difficulty: "Hard", tags: ["Creed"],
    question: "What is the acronym Creed writes on the board during a staff meeting when he briefly becomes manager?",
    answer: "BOBODY",
    distractors: ["WUPHF", "DUNDEE", "BIZNUS"] },
  { id: 153, category: "Episodes & Events", difficulty: "Hard", tags: ["Dwight", "Jim", "Pam", "Angela"],
    question: "After Angela dumps Dwight, what elaborate prank do Jim and Pam play on a severely depressed Dwight?",
    answer: "They pretend the Dunder Mifflin website has become self-aware and wants to outsell him",
    distractors: ["They send him love letters pretending to be from Angela", "They convince him Mose is planning to sell the farm", "They tell him he won a regional sales award"] },
  { id: 154, category: "Episodes & Events", difficulty: "Hard", tags: ["Michael"],
    question: "What does Michael win a gold medal for at the Office Olympics?",
    answer: "Closing on his condo",
    distractors: ["Winning the yogurt lid flipping contest", "Being the best boss", "Completing his fitness challenge"] },
  { id: 155, category: "Episodes & Events", difficulty: "Hard", tags: ["Michael"],
    question: "What percentage of Dunder Mifflin's revenue was at risk because of Michael's golden ticket idea?",
    answer: "50%",
    distractors: ["25%", "75%", "100%"] },
  { id: 156, category: "Episodes & Events", difficulty: "Hard", tags: ["Michael", "Angela", "Stanley"],
    question: "What rumor does Michael make up about Angela to cover for Stanley's affair?",
    answer: "That she is dating an 81-year-old billionaire who owns a Quizno's franchise",
    distractors: ["That she was a professional cat show judge", "That she once won a beauty pageant in another state", "That she had a secret twin sister"] },
  { id: 157, category: "Episodes & Events", difficulty: "Hard", tags: ["Dwight"],
    question: "In the 'Stress Relief' episode, what specific thing does Dwight put in the trash can to start the fire?",
    answer: "A lit cigarette",
    distractors: ["A match", "A candle", "A lighter and newspaper"] },
  { id: 158, category: "Episodes & Events", difficulty: "Hard", tags: ["Ryan", "Kelly"],
    question: "What is the date that Ryan and Kelly officially hooked up for the first time?",
    answer: "February 13th",
    distractors: ["February 14th", "March 17th", "December 31st"] },

  // ── QUOTES (Vol. 2) ───────────────────────────────────────────
  { id: 159, category: "Quotes", difficulty: "Easy", tags: ["Michael", "Pam"],
    question: "What does Michael say when Pam asks how he describes his management style?",
    answer: "'I'm like a boss, but also a friend. I am a... boss-friend.'",
    distractors: ["'I lead by following, and I follow by leading'", "'I'm not your boss, I'm your best friend who happens to be your boss'", "'I'm a people person who manages people'"] },
  { id: 160, category: "Quotes", difficulty: "Easy", tags: ["Kevin"],
    question: "According to Kevin, what is the trick to making his famous chili?",
    answer: "Undercooking the onions",
    distractors: ["Adding extra cumin", "Using three types of beans", "Slow-cooking it for 24 hours"] },
  { id: 162, category: "Quotes", difficulty: "Medium", tags: ["Dwight"],
    question: "What does Dwight say a beet farmer must have knowledge of?",
    answer: "Bears, beets, and Battlestar Galactica",
    distractors: ["Soil composition, rainfall, and crop rotation", "Farming, self-defense, and survival skills", "Tractor maintenance, irrigation, and accounting"] },
  { id: 163, category: "Quotes", difficulty: "Medium", tags: ["Michael"],
    question: "What phrase does Michael mangle when he means to say 'the tables have turned'?",
    answer: "'How the turntables...'",
    distractors: ["'How the tables have tabled'", "'Well well well, how the chairs have turned'", "'Oh how the turns have tabled'"] },
  { id: 164, category: "Quotes", difficulty: "Hard", tags: ["Michael", "Darryl"],
    question: "What is one of the fake interracial phrases Darryl teaches Michael, along with 'Fleece it out'?",
    answer: "'Pippity poppity gimme da zoppidy'",
    distractors: ["'Bippity boppity show me the zoppity'", "'Dinkin' flicka'", "'Zip it up and zip it out'"] },
  { id: 165, category: "Quotes", difficulty: "Hard", tags: ["Michael", "Jan"],
    question: "What resort do Michael and Jan stay at in Jamaica?",
    answer: "Sandals",
    distractors: ["Beaches", "Hedonism", "Club Med"] },
  { id: 166, category: "Quotes", difficulty: "Hard", tags: ["Gabe"],
    question: "What does Nellie say to Gabe that becomes a memorable put-down?",
    answer: "'Oh, get out, Skeleton Man!'",
    distractors: ["'Nobody asked you anything, ever'", "'You are a weirdo and everyone hates you'", "'You look like someone starved a butler'"] },
  { id: 167, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Who refers to himself as 'The Lizard King'?",
    answer: "Robert California",
    distractors: ["Dwight Schrute", "Michael Scott", "Creed Bratton"] },
  { id: 168, category: "Quotes", difficulty: "Hard", tags: ["Dwight", "Stanley"],
    question: "What does Stanley say when Dwight releases a bat into the office?",
    answer: "'Goodbye.'",
    distractors: ["'I'm going home.'", "'That is not my problem.'", "'Did I stutter?'"] },

  // ── BEHIND THE SCENES (Vol. 2) ────────────────────────────────
  { id: 169, category: "Behind the Scenes", difficulty: "Easy", tags: ["Michael", "Oscar"],
    question: "Was the kiss between Oscar and Michael in 'Gay Witch Hunt' scripted?",
    answer: "No: Steve Carell improvised it, kissing Oscar on the mouth when Oscar leaned in for a cheek kiss",
    distractors: ["Yes: it was in the original script from the beginning", "Partially: the hug was scripted but the kiss was improvised", "No: Oscar Nunez suggested it during rehearsal"] },
  { id: 170, category: "Behind the Scenes", difficulty: "Medium", tags: ["Jim", "Pam"],
    question: "What song was playing as Jim watched Pam drive away in 'The Dundies' episode?",
    answer: "'Tiny Dancer' by Elton John",
    distractors: ["'Your Song' by Elton John", "'Hallelujah' by Leonard Cohen", "'Yellow' by Coldplay"] },
  { id: 171, category: "Behind the Scenes", difficulty: "Medium", tags: ["Michael"],
    question: "Which celebrity walked past the camera while Michael was filming himself walking around New York City?",
    answer: "Conan O'Brien",
    distractors: ["Tina Fey", "Jerry Seinfeld", "David Letterman"] },
  { id: 172, category: "Behind the Scenes", difficulty: "Medium", tags: ["Dwight", "Jim", "Pam"],
    question: "What book does Dwight read to Jim and Pam during their first stay at Schrute Farms?",
    answer: "Harry Potter and the Deathly Hallows",
    distractors: ["Harry Potter and the Sorcerer's Stone", "The Lord of the Rings", "A Farmer's Almanac"] },
  { id: 173, category: "Behind the Scenes", difficulty: "Medium", tags: ["Angela"],
    question: "What real-life show did John Krasinski, Mindy Kaling, and Angela Kinsey all intern at before The Office?",
    answer: "Late Night with Conan O'Brien",
    distractors: ["Saturday Night Live", "The Daily Show with Jon Stewart", "Late Show with David Letterman"] },
  { id: 174, category: "Behind the Scenes", difficulty: "Medium", tags: ["Dwight"],
    question: "What prop did Dwight make for a birthday party that caused production to shut down from laughter?",
    answer: "A banner that read 'It is your birthday.'",
    distractors: ["A banner that read 'Congratulations on being born.'", "A banner that read 'You are one year closer to death.'", "A banner with just a photo of his own face"] },
  { id: 175, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "What was The Office's original working title before it launched in the US?",
    answer: "The American Workplace",
    distractors: ["The Paper Company", "Scranton", "The Cubicle"] },
  { id: 176, category: "Behind the Scenes", difficulty: "Hard", tags: ["Dwight", "Jim"],
    question: "How much did Jim spend on his costume when he dressed up as Dwight?",
    answer: "$11",
    distractors: ["$4", "$25", "$7"] },
  { id: 177, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "What happened to Rainn Wilson on the set of 'Beach Games' that sent a co-star to the hospital?",
    answer: "He accidentally got sand in Leslie David Baker's (Stanley's) eye, resulting in a scratched cornea",
    distractors: ["He tripped and fell into the bonfire, burning his arm", "He stepped on a jellyfish and needed medical attention", "He threw a football too hard and broke a camera"] },
  { id: 178, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "How many cold opens are there across The Office's nine seasons?",
    answer: "188",
    distractors: ["176", "201", "165"] },
  { id: 179, category: "Behind the Scenes", difficulty: "Hard", tags: ["Jim", "Pam"],
    question: "What were the five items Jim put in the teapot he gave Pam (not counting the note card)?",
    answer: "A cassette, Jim's high school yearbook photo, a Boggle timer, hot sauce, and a mini golf pencil",
    distractors: ["A letter, Jim's college ID, a dice, Tabasco sauce, and a crayon", "A mixtape, a class photo, a deck of cards, ketchup packets, and a pencil", "A CD, Jim's diploma, a coin, a candy bar, and a bookmark"] },

  // ── RELATIONSHIPS & ROMANCE (Vol. 2) ──────────────────────────
  { id: 180, category: "Relationships & Romance", difficulty: "Easy", tags: ["Michael"],
    question: "Whose mother does Michael briefly date?",
    answer: "Pam's mother, Helene",
    distractors: ["Jim's mother, Larissa", "Dwight's mother, Hedda", "Angela's mother, Janet"] },
  { id: 181, category: "Relationships & Romance", difficulty: "Easy", tags: ["Erin"],
    question: "Who does Erin initially think might be her biological mother?",
    answer: "Phyllis",
    distractors: ["Meredith", "Angela", "Jan Levinson"] },
  { id: 182, category: "Relationships & Romance", difficulty: "Medium", tags: ["Michael"],
    question: "How many women does Michael Scott propose marriage to over the course of the show?",
    answer: "Two: Carol and Holly",
    distractors: ["Three: Carol, Jan, and Holly", "One: Holly", "Two: Jan and Holly"] },
  { id: 183, category: "Relationships & Romance", difficulty: "Medium", tags: ["Pam", "Roy"],
    question: "If Pam had married Roy, what would her full married name have been?",
    answer: "Pamela Anderson",
    distractors: ["Pamela Anderson-Beesly", "Patricia Anderson", "Pamela Roy"] },
  { id: 184, category: "Relationships & Romance", difficulty: "Medium", tags: ["Michael", "Pam"],
    question: "Why does Pam slap Michael Scott?",
    answer: "He tells everyone that Pam's mom came onto him",
    distractors: ["He made fun of her art at the gallery show", "He called off their lunch plans for the third time", "He fired her without warning"] },
  { id: 185, category: "Relationships & Romance", difficulty: "Medium", tags: ["Karen"],
    question: "What branch of Dunder Mifflin does Karen Filippelli end up managing after leaving Scranton?",
    answer: "Dunder Mifflin Utica",
    distractors: ["Dunder Mifflin Nashua", "Dunder Mifflin Albany", "Dunder Mifflin Buffalo"] },
  { id: 186, category: "Relationships & Romance", difficulty: "Medium", tags: [],
    question: "Who gets publicly dumped at the Dundies in season 7?",
    answer: "Gabe Lewis (dumped by Erin)",
    distractors: ["Andy Bernard (dumped by Angela)", "Ryan Howard (dumped by Kelly)", "Michael Scott (dumped by Jan)"] },
  { id: 187, category: "Relationships & Romance", difficulty: "Medium", tags: ["Angela", "Andy"],
    question: "How did Andy first ask Angela out?",
    answer: "He gave her a cat he trapped outside Vance Refrigeration",
    distractors: ["He serenaded her in the break room with his banjo", "He left roses on her desk every day for a week", "He baked her a cake shaped like a cat"] },
  { id: 188, category: "Relationships & Romance", difficulty: "Hard", tags: ["Roy", "Dwight"],
    question: "What do Roy and Dwight have in common in the series finale?",
    answer: "Both are seen to have found happiness, Roy with his wife and Dwight with Angela after they finally marry",
    distractors: ["Both moved away from Scranton to start new businesses", "Both proposed to their partners during the documentary screening", "Both were promoted to management positions at their jobs"] },
  { id: 189, category: "Relationships & Romance", difficulty: "Hard", tags: ["Phyllis", "Stanley"],
    question: "What heartwarming gift does Stanley give Phyllis in the series finale?",
    answer: "A wooden carving of her with flamingo legs",
    distractors: ["A painting he made of the Dunder Mifflin office", "A book of crossword puzzles he hand-wrote", "A framed photo of them from their first day at the office"] },

  // ── COLD OPENS & RUNNING GAGS ─────────────────────────────────
  { id: 191, category: "Cold Opens & Running Gags", difficulty: "Easy", tags: ["Dwight"],
    question: "What animal does Dwight release into the office by trapping it on someone's head in a garbage bag?",
    answer: "A bat",
    distractors: ["A bird", "A raccoon", "A squirrel"] },
  { id: 192, category: "Cold Opens & Running Gags", difficulty: "Easy", tags: ["Dwight"],
    question: "Which character does the bat bite after Dwight traps it?",
    answer: "Meredith",
    distractors: ["Angela", "Kevin", "Phyllis"] },
  { id: 194, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: ["Dwight", "Angela", "Oscar"],
    question: "What is the name of the cat Angela throws to Oscar through the ceiling during Dwight's fire drill cold open?",
    answer: "Bandit",
    distractors: ["Sprinkles", "Princess Lady", "Mr. Ash"] },
  { id: 195, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: [],
    question: "Who kicks in the vending machine glass during the fire drill cold open?",
    answer: "Kevin Malone",
    distractors: ["Stanley Hudson", "Dwight Schrute", "Darryl Philbin"] },
  { id: 196, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: ["Dwight"],
    question: "What is Dwight's favorite TV show?",
    answer: "Battlestar Galactica",
    distractors: ["Star Trek", "The X-Files", "Doctor Who"] },
  { id: 197, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: ["Dwight", "Jim"],
    question: "Besides Jell-O, what other food does Jim put Dwight's stapler in at one point?",
    answer: "A giant meatball",
    distractors: ["A block of ice", "A cake", "A fish tank"] },
  { id: 198, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: [],
    question: "What are the three main events of the Office Olympics?",
    answer: "Flonkerton (box of paper snowshoe racing), Hate Ball, and Who Can Fit the Most M&Ms in Their Mouth",
    distractors: ["Dunderball, Chair Racing, and Paper Airplane Toss", "Box Relay, Trashketball, and Rubber Band Archery", "Stapler Javelin, Office Chair Relay, and Paper Football"] },
  { id: 199, category: "Cold Opens & Running Gags", difficulty: "Hard", tags: ["Dwight", "Jim", "Pam"],
    question: "What does Jim do to make Dwight think he can move a coat rack with his mind?",
    answer: "Pam pulls it back and forth using an umbrella hidden under her desk",
    distractors: ["Jim ties fishing line to the coat rack from his desk", "Andy pushes it from behind the wall on cue", "Jim uses a remote-controlled device attached to the base"] },
  { id: 200, category: "Cold Opens & Running Gags", difficulty: "Hard", tags: ["Dwight"],
    question: "After finding half a joint in the parking lot during 'Drug Testing,' who fake-cries during Dwight's investigation?",
    answer: "Jim Halpert",
    distractors: ["Kevin Malone", "Ryan Howard", "Andy Bernard"] },

  // ── LOCATIONS & MISCELLANEOUS (Vol. 2) ────────────────────────
  { id: 201, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "What is the name of the Dunder Mifflin Scranton office building?",
    answer: "Scranton Business Park",
    distractors: ["Scranton Commerce Center", "Dunder Mifflin Plaza", "Lackawanna Office Park"] },
  { id: 202, category: "Locations & Miscellaneous", difficulty: "Easy", tags: ["Jim"],
    question: "Which branch of Dunder Mifflin does Jim transfer to after season 2?",
    answer: "Dunder Mifflin Stamford",
    distractors: ["Dunder Mifflin Utica", "Dunder Mifflin Nashua", "Dunder Mifflin Albany"] },
  { id: 203, category: "Locations & Miscellaneous", difficulty: "Easy", tags: ["Michael"],
    question: "What brand of clothing is Michael Scott accidentally wearing when he buys a woman's suit?",
    answer: "MISSterious",
    distractors: ["MISSplaced", "Ms. Taken", "FEMale Fit"] },
  { id: 204, category: "Locations & Miscellaneous", difficulty: "Easy", tags: ["Pam"],
    question: "What is the name of Pam's friend from art school?",
    answer: "Alex",
    distractors: ["Jamie", "Ben", "Marcus"] },
  { id: 205, category: "Locations & Miscellaneous", difficulty: "Easy", tags: ["Kevin"],
    question: "What actress played Dakota, the accountant who replaced Kevin in the series finale?",
    answer: "Dakota Johnson",
    distractors: ["Aubrey Plaza", "Anna Kendrick", "Emma Stone"] },
  { id: 206, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Michael", "Pam"],
    question: "What does Michael say to Pam about where to put the fax from corporate in the very first episode?",
    answer: "He tells her to put it in a special filing cabinet, which is the garbage can",
    distractors: ["He tells her to fax it back with a funny note", "He says to file it under 'important things I'll never read'", "He tells her to shred it because he doesn't trust corporate"] },
  { id: 207, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Roy"],
    question: "Where does Roy work after leaving Dunder Mifflin?",
    answer: "A vitamin store",
    distractors: ["A gravel company", "A sporting goods store", "A car dealership"] },
  { id: 208, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Michael", "Darryl"],
    question: "What celebrity does Darryl say Michael looks like while wearing the women's suit?",
    answer: "Hillary Clinton",
    distractors: ["Ellen DeGeneres", "Martha Stewart", "Oprah Winfrey"] },
  { id: 209, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Jim", "Darryl"],
    question: "Which three coworkers does Jim practice ping pong with before his rematch against Darryl?",
    answer: "Kevin, Meredith, and Dwight",
    distractors: ["Andy, Phyllis, and Stanley", "Oscar, Creed, and Ryan", "Toby, Angela, and Kelly"] },
  { id: 210, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Michael", "Jan"],
    question: "What is the name of the person Michael and Jan meet at Chili's in 'The Client' episode?",
    answer: "Christian",
    distractors: ["Tim", "Brad", "Marcus"] },
  { id: 211, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Kelly"],
    question: "What costume is Carol wearing when she shows up to Kelly's Diwali party?",
    answer: "A cheerleader costume",
    distractors: ["A nurse costume", "A princess costume", "A witch costume"] },
  { id: 212, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Oscar", "Creed"],
    question: "What does Oscar get for Creed in the Secret Santa exchange and why?",
    answer: "A shamrock keychain, because he thinks Creed is Irish",
    distractors: ["A bottle of whiskey, because he thinks Creed is a heavy drinker", "A fishing lure, because he heard Creed likes the outdoors", "A pair of sunglasses, because Creed always wears them"] },
  { id: 213, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Michael", "Ryan"],
    question: "What does Michael give Ryan as a Christmas gift, with the price tag still on?",
    answer: "A $400 iPod",
    distractors: ["A $300 leather briefcase", "A $200 watch", "A $500 gift card"] },
  { id: 214, category: "Locations & Miscellaneous", difficulty: "Medium", tags: ["Michael", "Jim"],
    question: "What song do Michael and Jim sing together after Michael crashes Jim's backyard barbecue?",
    answer: "'Islands in the Stream' by Kenny Rogers and Dolly Parton",
    distractors: ["'Endless Love' by Lionel Richie and Diana Ross", "'Summer Nights' from Grease", "'Don't Go Breaking My Heart' by Elton John and Kiki Dee"] },
  { id: 215, category: "Locations & Miscellaneous", difficulty: "Hard", tags: ["Toby"],
    question: "What is Toby's daughter's name?",
    answer: "Sasha",
    distractors: ["Emily", "Rachel", "Sophie"] },
  { id: 216, category: "Locations & Miscellaneous", difficulty: "Hard", tags: ["Pam"],
    question: "What is Pam's middle name?",
    answer: "Morgan",
    distractors: ["Marie", "Anne", "Elizabeth"] },
  { id: 217, category: "Locations & Miscellaneous", difficulty: "Hard", tags: ["Michael", "Dwight", "Jan"],
    question: "What fruit does Dwight use to simulate childbirth to help Michael prepare for Jan's baby being born?",
    answer: "A watermelon",
    distractors: ["A pumpkin", "A cantaloupe", "A bowling ball"] },
  { id: 218, category: "Locations & Miscellaneous", difficulty: "Hard", tags: ["Michael", "Stanley"],
    question: "What does Stanley do to Michael's car after Michael tells Stanley's wife about his affair?",
    answer: "He smashes it with a tire iron",
    distractors: ["He keys it in the parking lot", "He slashes the tires", "He covers it in Post-it notes"] },
  { id: 219, category: "Locations & Miscellaneous", difficulty: "Hard", tags: ["Dwight", "Jim"],
    question: "What was the name of the Asian actor who played 'Asian Jim' in the prank on Dwight?",
    answer: "Randall Park (his character's name was Steve)",
    distractors: ["Steven Yeun", "John Cho", "Ken Jeong"] },
  { id: 220, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "Which character is arrested and later revealed to have faked their own death in the series finale?",
    answer: "Creed Bratton",
    distractors: ["Kevin Malone", "Meredith Palmer", "Ryan Howard"] },

  // ── DUNDER MIFFLIN COMPANY ────────────────────────────────────
  { id: 221, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "Who is the founder of Dunder Mifflin Paper Company?",
    answer: "Robert Dunder and Robert Mifflin",
    distractors: ["Robert Dunder and Sons", "William Mifflin and Bill Dunder", "Howard Dunder and Neil Mifflin"] },

  { id: 222, category: "Characters", difficulty: "Medium", tags: [],
    question: "Who is the CFO of Dunder Mifflin Paper Company?",
    answer: "David Wallace",
    distractors: ["Jan Levinson", "Charles Miner", "Robert California"] },

  { id: 223, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "How many branches of Dunder Mifflin were shown or mentioned throughout the show?",
    answer: "8",
    distractors: ["6", "10", "12"] },

  { id: 224, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What is the official slogan of Dunder Mifflin Paper Company?",
    answer: "Limitless paper in a paperless world.",
    distractors: ["The people person's paper people", "Quality paper for quality people", "Paper you can trust in a digital world"] },

  { id: 225, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "What embarrassing mistake does Dunder Mifflin make on a batch of paper that leads to a major PR crisis?",
    answer: "They accidentally print an obscene watermark on the paper",
    distractors: ["They ship a competitor's logo by mistake", "A rival company hijacks their paper supply chain", "Blank reams are mislabeled as premium stock"] },

  { id: 226, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "Which city is the corporate headquarters of Dunder Mifflin located in?",
    answer: "New York City",
    distractors: ["Scranton, Pennsylvania", "Albany, New York", "Philadelphia, Pennsylvania"] },

  { id: 227, category: "Locations & Miscellaneous", difficulty: "Easy", tags: [],
    question: "Which Dunder Mifflin branch was shut down and merged with Scranton in Season 3?",
    answer: "The Stamford branch",
    distractors: ["The Utica branch", "The Nashua branch", "The Albany branch"] },

  { id: 228, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "In the episode 'Branch Wars,' why does Michael want to prank the Utica branch?",
    answer: "Because Stanley was offered a job there",
    distractors: ["Because the Utica branch poached a major client from Scranton", "Because Michael was passed over for a promotion that went to the Utica manager", "Because the Utica branch filed a complaint against the Scranton branch"] },

  { id: 229, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What catchy slogan is used in Dunder Mifflin's company jingle featured in Season 3?",
    answer: "The people person's paper people",
    distractors: ["Limitless paper in a paperless world", "Quality paper for quality people", "Paper for a better tomorrow"] },

  { id: 230, category: "Locations & Miscellaneous", difficulty: "Hard", tags: [],
    question: "Which branch is mentioned as being located closest to Scranton?",
    answer: "Binghamton, New York",
    distractors: ["Utica, New York", "Albany, New York", "Nashua, New Hampshire"] },

  { id: 231, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What major event do all Dunder Mifflin branches attend together once a year?",
    answer: "The company picnic",
    distractors: ["The regional sales conference", "The annual awards ceremony", "The Dunder Mifflin Invitational"] },

  // ── CHARACTERS (Vol. 3) ───────────────────────────────────────
  { id: 232, category: "Characters", difficulty: "Medium", tags: ["Michael"],
    question: "What's the title of Michael Scott's self-written book?",
    answer: "Somehow I Manage",
    distractors: ["Managing with Heart", "The Michael Scott Method", "World's Best Boss: A Memoir"] },

  { id: 233, category: "Characters", difficulty: "Hard", tags: ["Pam"],
    question: "What yogurt flavor does Pam like the most?",
    answer: "Mixed berry",
    distractors: ["Strawberry", "Peach", "Vanilla"] },

  { id: 234, category: "Characters", difficulty: "Hard", tags: ["Dwight"],
    question: "What does Dwight call his pet porcupine?",
    answer: "Henrietta",
    distractors: ["Brunhilde", "Beatrice", "Helga"] },

  { id: 235, category: "Characters", difficulty: "Easy", tags: ["Jan"],
    question: "What is the name of Jan's candle business she starts after being fired?",
    answer: "Serenity by Jan",
    distractors: ["Jan's Aromatics", "Candles by Jan", "Luxe by Jan Levinson"] },

  { id: 236, category: "Characters", difficulty: "Medium", tags: ["Pam"],
    question: "What art school does Pam attend in New York?",
    answer: "The Pratt Institute",
    distractors: ["The Art Institute of New York", "NYU", "New York Academy of Art"] },

  { id: 237, category: "Characters", difficulty: "Easy", tags: ["Andy"],
    question: "What college did Andy Bernard attend and frequently mention?",
    answer: "Cornell University",
    distractors: ["Yale University", "Harvard University", "Dartmouth College"] },

  { id: 238, category: "Music & Performances", difficulty: "Easy", tags: ["Andy"],
    question: "What musical instrument does Andy often play in the office?",
    answer: "Banjo",
    distractors: ["Guitar", "Ukulele", "Mandolin"] },

  { id: 239, category: "Characters", difficulty: "Hard", tags: ["Michael"],
    question: "What middle name is revealed for Michael Scott in the series?",
    answer: "Gary",
    distractors: ["James", "Alan", "Scott"] },

  { id: 240, category: "Characters", difficulty: "Easy", tags: [],
    question: "What is the name of the warehouse foreman at the Scranton branch of Dunder Mifflin?",
    answer: "Darryl Philbin",
    distractors: ["Roy Anderson", "Lonny Collins", "Hidetoshi Hasegawa"] },

  { id: 241, category: "Characters", difficulty: "Easy", tags: ["Stanley"],
    question: "What is Stanley Hudson's favorite work day?",
    answer: "Pretzel Day",
    distractors: ["Hawaiian Shirt Day", "Casual Friday", "Bring Your Kid to Work Day"] },

  { id: 242, category: "Episodes & Events", difficulty: "Medium", tags: ["Ryan"],
    question: "What is the name of Ryan Howard's startup company?",
    answer: "WUPHF.com",
    distractors: ["TempNation.org", "HowardTechnologies.com", "RealTalk.com"] },

  { id: 243, category: "Characters", difficulty: "Medium", tags: ["Angela"],
    question: "What is the name of Angela Martin's state senator husband?",
    answer: "Robert Lipton",
    distractors: ["Robert California", "Senator David Clark", "Senator James Harrison"] },

  { id: 244, category: "Characters", difficulty: "Hard", tags: ["Darryl"],
    question: "What is the name of Darryl Philbin's daughter?",
    answer: "Jada",
    distractors: ["Jasmine", "Jordan", "Maya"] },

  { id: 245, category: "Characters", difficulty: "Medium", tags: ["Jan"],
    question: "What is the name of Jan Levinson's daughter?",
    answer: "Astrid",
    distractors: ["Ingrid", "Petra", "Helene"] },

  // ── BEHIND THE SCENES (Vol. 3) ────────────────────────────────
  { id: 246, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "Where was the exterior shot of the Dunder Mifflin Scranton branch filmed?",
    answer: "Panorama City, California",
    distractors: ["Burbank, California", "Van Nuys, California", "Woodland Hills, California"] },

  { id: 247, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "Where was the Steamtown Mall location used in the show?",
    answer: "Westfield Topanga Mall in Canoga Park, California",
    distractors: ["Westfield Century City in Los Angeles, California", "The Burbank Town Center in Burbank, California", "The Glendale Galleria in Glendale, California"] },

  { id: 251, category: "Behind the Scenes", difficulty: "Easy", tags: [],
    question: "What British comedian co-created the original UK version of The Office?",
    answer: "Ricky Gervais",
    distractors: ["Stephen Merchant", "Karl Pilkington", "Steve Coogan"] },

  { id: 252, category: "Behind the Scenes", difficulty: "Hard", tags: [],
    question: "Who composed The Office theme song?",
    answer: "Jay Ferguson",
    distractors: ["Greg Daniels", "Michael Schur", "Thomas Newman"] },

  { id: 253, category: "Behind the Scenes", difficulty: "Medium", tags: [],
    question: "Which cast member who played Mose also co-created another popular sitcom, Parks and Recreation?",
    answer: "Michael Schur",
    distractors: ["Greg Daniels", "B.J. Novak", "Paul Lieberstein"] },

  // ── EPISODES & EVENTS (Vol. 3) ────────────────────────────────
  { id: 248, category: "Episodes & Events", difficulty: "Medium", tags: ["Pam"],
    question: "What restaurant did Pam get banned from after drinking too much?",
    answer: "Chili's",
    distractors: ["Benihana", "Poor Richard's", "Applebee's"] },

  { id: 249, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "Where did Michael take the team for Booze Cruise?",
    answer: "Lake Wallenpaupack",
    distractors: ["Lake Scranton", "Atlantic Ocean", "the Susquehanna River"] },

  { id: 250, category: "Locations & Miscellaneous", difficulty: "Medium", tags: [],
    question: "What is the name of the bar where the Scranton crew often hangs out?",
    answer: "Poor Richard's",
    distractors: ["McGillicuddy's Pub", "Cooler's Bar", "Slack's Tavern"] },

  { id: 254, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In Season 2, what theme did the Dunder Mifflin Christmas party have?",
    answer: "Yankee Swap (a.k.a. White Elephant)",
    distractors: ["Winter Wonderland", "Secret Santa", "Moroccan Christmas"] },

  { id: 255, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "In the 'Pool Party' episode, whose pool party is the office invited to?",
    answer: "Robert California's",
    distractors: ["Andy Bernard's", "Dwight Schrute's", "David Wallace's"] },

  { id: 256, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "What event does the 'Niagara' two-part episode revolve around?",
    answer: "Jim and Pam's wedding",
    distractors: ["Dwight and Angela's engagement party", "Michael's farewell party", "The Dunder Mifflin company anniversary"] },

  { id: 257, category: "Episodes & Events", difficulty: "Medium", tags: ["Phyllis"],
    question: "What theme does Phyllis choose when she takes over the Christmas party in Season 5?",
    answer: "Moroccan theme",
    distractors: ["Winter Wonderland", "Yankee Swap", "Hawaiian theme"] },

  { id: 258, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "What is Michael forced to do during the Halloween episode in Season 2?",
    answer: "Fire someone",
    distractors: ["Wear a costume all day", "Attend sensitivity training", "Apologize to the entire office"] },

  { id: 259, category: "Episodes & Events", difficulty: "Easy", tags: [],
    question: "During the 'Fun Run' charity event, what is the cause the office is supporting?",
    answer: "Rabies awareness",
    distractors: ["Breast cancer research", "Hunger relief", "Animal shelter funding"] },

  { id: 260, category: "Episodes & Events", difficulty: "Medium", tags: ["Dwight"],
    question: "What type of party does Dwight host at Schrute Farms for the office team?",
    answer: "Garden party",
    distractors: ["Beet harvest festival", "Christmas party", "Birthday party"] },

  { id: 267, category: "Episodes & Events", difficulty: "Medium", tags: [],
    question: "In 'Office Olympics,' what unusual medal do winners receive?",
    answer: "Yogurt lids",
    distractors: ["Paper clip chains", "Bottle cap ribbons", "Sticky note stars"] },

  { id: 268, category: "Episodes & Events", difficulty: "Easy", tags: ["Michael"],
    question: "In 'Scott's Tots,' what does Michael bring as a replacement gift for the students?",
    answer: "Laptop batteries",
    distractors: ["Gift cards", "Coupon booklet", "Notebooks and pens"] },

  { id: 266, category: "Episodes & Events", difficulty: "Medium", tags: ["Dwight"],
    question: "What is the name of Dwight's family Christmas tradition celebration?",
    answer: "Belsnickel",
    distractors: ["Schrute Fun Family Christmas", "The Schrute Harvest Festival", "Bratwurst Day"] },

  { id: 265, category: "Episodes & Events", difficulty: "Easy", tags: ["Michael"],
    question: "What is the name of the movie Michael Scott writes and stars in?",
    answer: "Threat Level Midnight",
    distractors: ["Agent Michael: The Movie", "Scranton Nights", "The Michael Scott Story"] },

  { id: 270, category: "Episodes & Events", difficulty: "Hard", tags: ["Michael"],
    question: "In 'Money,' which unusual piece of technology does Michael purchase for his condo that contributes to his financial problems?",
    answer: "An exercise machine called 'Core Blaster Extreme'",
    distractors: ["A home theater system", "A robotic vacuum cleaner", "A high-end treadmill"] },

  { id: 271, category: "Episodes & Events", difficulty: "Medium", tags: ["Dwight"],
    question: "In the 'Launch Party' episode, who did Dwight challenge to prove he is a better salesman than technology?",
    answer: "Dunder Mifflin Infinity website",
    distractors: ["Ryan Howard", "Jim Halpert", "A sales rep from Staples"] },

  { id: 272, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "In 'Dinner Party,' what small gadget does Michael proudly show off in his condo as his prized possession?",
    answer: "His tiny plasma TV",
    distractors: ["A high-end stereo system", "A cappuccino machine", "A mini fridge"] },

  { id: 274, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "In 'The Office Olympics,' who wins the gold medal in the game of 'Flonkerton'?",
    answer: "Phyllis",
    distractors: ["Pam", "Kevin", "Oscar"] },

  { id: 275, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "In 'Beach Games,' what does Michael tell everyone the winner will receive?",
    answer: "His job as Regional Manager",
    distractors: ["A cash prize of $1,000", "A work trip to Canada", "Employee of the year award"] },

  { id: 276, category: "Episodes & Events", difficulty: "Hard", tags: [],
    question: "Who wins the paper airplane contest in Season 9?",
    answer: "Toby",
    distractors: ["Dwight", "Jim", "Kevin"] },

  { id: 277, category: "Episodes & Events", difficulty: "Medium", tags: ["Michael"],
    question: "In 'Murder,' what game does Michael introduce to distract everyone from bad company news?",
    answer: "Belles, Bourbon, and Bullets",
    distractors: ["Clue", "Murder in the Manor", "Southern Comfort Mystery"] },

  // ── COLD OPENS & RUNNING GAGS (Vol. 2) ───────────────────────
  { id: 261, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: ["Jim", "Andy"],
    question: "What does Jim put in Andy's office ceiling to annoy him as a prank?",
    answer: "His cell phone",
    distractors: ["A radio", "An alarm clock", "A walkie talkie"] },

  { id: 262, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: ["Andy"],
    question: "Who encased Andy's calculator in Jell-O?",
    answer: "Jim",
    distractors: ["Dwight", "Pam", "Ryan"] },

  { id: 264, category: "Cold Opens & Running Gags", difficulty: "Medium", tags: ["Jim", "Dwight"],
    question: "What did Jim name his team in response to Dwight naming his as Gryffindor?",
    answer: "Voldemort",
    distractors: ["Slytherin", "Hufflepuff", "Skywalker"] },

  // ── EPISODES & EVENTS (Pranks & Parties) ─────────────────────
  { id: 263, category: "Episodes & Events", difficulty: "Medium", tags: ["Jim", "Phyllis"],
    question: "Who did Jim hire for Phyllis's bachelorette party?",
    answer: "A Benjamin Franklin impersonator",
    distractors: ["A male stripper", "A stand-up comedian", "A fortune teller"] },

  // ── CHARACTERS (Vol. 4) ───────────────────────────────────────
  { id: 269, category: "Characters", difficulty: "Medium", tags: [],
    question: "Who invented the Suck It vacuum-like invention in The Office?",
    answer: "David Wallace",
    distractors: ["Dwight Schrute", "Ryan Howard", "Hank Doyle"] },

  // ── RELATIONSHIPS & ROMANCE (Vol. 3) ─────────────────────────
  { id: 273, category: "Relationships & Romance", difficulty: "Hard", tags: ["Darryl"],
    question: "What romantic partner does Darryl Philbin pursue after moving to the upstairs office?",
    answer: "Val Johnson",
    distractors: ["Kelly Kapoor", "Donna Newton", "Nellie Bertram"] },

  // ── MUSIC & PERFORMANCES (Vol. 2) ────────────────────────────
  { id: 278, category: "Music & Performances", difficulty: "Medium", tags: ["Andy"],
    question: "In 'Andy's Play,' which musical does Andy perform in for his community theater show?",
    answer: "Sweeney Todd",
    distractors: ["Les Miserables", "The Phantom of the Opera", "Cats"] },

  // ── QUOTES (Vol. 3) ───────────────────────────────────────────
  { id: 279, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Who said, 'Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.'",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Robert California", "Andy Bernard"] },

  { id: 280, category: "Quotes", difficulty: "Hard", tags: [],
    question: "'If I had to, I could clean out my desk in five seconds, and nobody would ever know that I'd ever been here. And I'd forget, too.' Who said this quote?",
    answer: "Ryan Howard",
    distractors: ["Toby Flenderson", "Jim Halpert", "Kelly Kapoor"] },

  { id: 281, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Who said this line: 'Boy have you done lost your mind, 'cause I'll help you find it!'",
    answer: "Stanley Hudson",
    distractors: ["Darryl Philbin", "Michael Scott", "Kevin Malone"] },

  { id: 282, category: "Quotes", difficulty: "Medium", tags: [],
    question: "'I love inside jokes. I'd love to be a part of one someday.' Which character quoted this line?",
    answer: "Michael Scott",
    distractors: ["Andy Bernard", "Kevin Malone", "Toby Flenderson"] },

  { id: 283, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Who said: 'I just want to lie on the beach and eat hot dogs. That's all I've ever wanted.'",
    answer: "Kevin Malone",
    distractors: ["Michael Scott", "Darryl Philbin", "Creed Bratton"] },

  { id: 284, category: "Quotes", difficulty: "Hard", tags: [],
    question: "'Do I need to be liked? Absolutely not. I like to be liked. I enjoy being liked. I have to be liked, but it's not like this compulsive need to be liked, like my need to be praised.' Who said this line?",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Andy Bernard", "Robert California"] },

  { id: 285, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Who said: 'I am running away from my responsibilities. And it feels good.'",
    answer: "Michael Scott",
    distractors: ["Dwight Schrute", "Ryan Howard", "Kevin Malone"] },

  { id: 286, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Which character said, 'The real crime, I think, was the beard.'",
    answer: "Oscar Martinez",
    distractors: ["Kevin Malone", "Toby Flenderson", "Jim Halpert"] },

  { id: 287, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Who said: 'Sometimes I'll start a sentence and I don't even know where it's going. I just hope I find it along the way, like an improv conversation...an improversation.'",
    answer: "Michael Scott",
    distractors: ["Andy Bernard", "Kevin Malone", "Dwight Schrute"] },

  { id: 288, category: "Quotes", difficulty: "Hard", tags: [],
    question: "'It's true. Around this office, in the past, I have been a little abrupt with people. But the doctor said if I can't find a new way to relate more positively to my surroundings, I'm going to die.' Who quoted this line?",
    answer: "Stanley Hudson",
    distractors: ["Michael Scott", "Dwight Schrute", "Angela Martin"] },

  { id: 289, category: "Quotes", difficulty: "Hard", tags: [],
    question: "Who said, 'Close your mouth, sweetie. You look like a trout.'",
    answer: "Phyllis Vance",
    distractors: ["Angela Martin", "Jan Levinson", "Kelly Kapoor"] },

  { id: 290, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Which character quoted: 'I am Beyonce, always.'",
    answer: "Michael Scott",
    distractors: ["Kelly Kapoor", "Ryan Howard", "Erin Hannon"] },

  { id: 291, category: "Quotes", difficulty: "Easy", tags: [],
    question: "Who said this hilarious line: 'Why waste time use lot word when few word do trick?'",
    answer: "Kevin Malone",
    distractors: ["Michael Scott", "Creed Bratton", "Dwight Schrute"] },

  { id: 292, category: "Quotes", difficulty: "Medium", tags: [],
    question: "Who said, 'I wish there was a way to know you're in the good old days before you've actually left them'?",
    answer: "Andy Bernard",
    distractors: ["Michael Scott", "Jim Halpert", "Pam Beesly"] },

  { id: 293, category: "Quotes", difficulty: "Medium", tags: [],
    question: "'Through concentration, I can raise and lower my cholesterol at will.' Who said it?",
    answer: "Dwight Schrute",
    distractors: ["Michael Scott", "Creed Bratton", "Robert California"] },

  { id: 294, category: "Quotes", difficulty: "Medium", tags: [],
    question: "There's a lot of beauty in ordinary things. Isn't that kind of the point? Who said this in the final episode?",
    answer: "Pam Beesly",
    distractors: ["Jim Halpert", "Michael Scott", "Holly Flax"] },

];

// ── QUOTE REACTIONS ───────────────────────────────────────────────
const QUOTES = {
  correct: [
    { text: "I'm not superstitious, but I am a little stitious, and I knew you'd get that right.", character: "Michael Scott", citation: null },
    { text: "FACT. That answer is correct.", character: "Dwight Schrute", citation: null },
    { text: "That's what she said.", character: "Michael Scott", citation: "S2E2" },
    { text: "I am Beyoncé, always.", character: "Michael Scott", citation: null },
    { text: "You have no idea how high I can fly right now.", character: "Michael Scott", citation: null },
    { text: "Identity theft is not a joke, Jim, but that answer was no joke either.", character: "Dwight Schrute", citation: null },
    { text: "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love my correct answers.", character: "Michael Scott", citation: null },
    { text: "You are a great man. Today, you have shown that.", character: "Michael Scott", citation: null },
    { text: "Bears. Beets. Battlestar Galactica. Correct answers.", character: "Jim Halpert", citation: null },
    { text: "Whenever I'm about to do something, I think: would an idiot do this? You clearly did not do that.", character: "Dwight Schrute", citation: null },
    { text: "You have passed the Schrute test. Few do.", character: "Dwight Schrute", citation: null },
    { text: "As your regional manager, I want to say: well done. I am so proud. Don't make it weird.", character: "Michael Scott", citation: null },
    { text: "I'm not going to say you're a genius. I'm going to say you're a genius.", character: "Michael Scott", citation: null },
    { text: "The people person's paper people salute you.", character: "Michael Scott", citation: null },
    { text: "How the turntables... have turned. In your favor.", character: "Michael Scott", citation: null },
  ],
  incorrect: [
    { text: "Why are you the way that you are?", character: "Michael Scott", citation: "S2E12" },
    { text: "I... DECLARE... BANKRUPTCY... of knowledge.", character: "Michael Scott", citation: null },
    { text: "That is incorrect. FACT.", character: "Dwight Schrute", citation: null },
    { text: "This is the worst thing that has ever happened. In the history of the world.", character: "Michael Scott", citation: null },
    { text: "I'm not mad. I'm just disappointed. Actually I'm both. I'm a little mad.", character: "Michael Scott", citation: null },
    { text: "This is an environment of welcoming, and you have not been welcomed.", character: "Michael Scott", citation: "S1E2" },
    { text: "You have failed this office.", character: "Dwight Schrute", citation: null },
    { text: "How the turntables... have not turned for you today.", character: "Michael Scott", citation: null },
    { text: "Webster's Dictionary defines 'wrong' as... well, that. What you just did.", character: "Michael Scott", citation: null },
    { text: "I knew it. I knew you didn't know that. I said it before and I'll say it again.", character: "Dwight Schrute", citation: null },
    { text: "Oh no. Oh, this is bad. This is very bad.", character: "Kevin Malone", citation: null },
    { text: "That answer is like a Toby answer. And nobody wants that.", character: "Michael Scott", citation: null },
    { text: "You had ONE job. Not literally, you have many jobs. But on this question: one job.", character: "Michael Scott", citation: null },
    { text: "No. No no no no no. Also no.", character: "Michael Scott", citation: null },
    { text: "I'm not angry. I'm just going to need you to go ahead and try that again.", character: "Michael Scott", citation: null },
  ]
};

// ── CATEGORIES & DIFFICULTIES ─────────────────────────────────────
const CATEGORIES = [
  "Characters",
  "Episodes & Events",
  "Quotes",
  "Behind the Scenes",
  "Relationships & Romance",
  "Music & Performances",
  "Locations & Miscellaneous",
  "Cold Opens & Running Gags"
];

const DIFFICULTIES = ["Easy", "Medium", "Hard"];

// ── CHARACTER TAGS ────────────────────────────────────────────────
// Used for auto-tagging questions and populating the character filter dropdown.
// `patterns` are searched (whole-word, case-insensitive) in question + answer text.
const CHARACTER_TAGS = [
  { tag: 'Michael',           label: 'Michael Scott',      patterns: ['Michael Scott', 'Michael'] },
  { tag: 'Dwight',            label: 'Dwight Schrute',     patterns: ['Dwight Schrute', 'Dwight'] },
  { tag: 'Jim',               label: 'Jim Halpert',        patterns: ['Jim Halpert', 'Jim'] },
  { tag: 'Pam',               label: 'Pam Beesly',         patterns: ['Pam Beesly', 'Pam'] },
  { tag: 'Ryan',              label: 'Ryan Howard',        patterns: ['Ryan Howard', 'Ryan'] },
  { tag: 'Kelly',             label: 'Kelly Kapoor',       patterns: ['Kelly Kapoor', 'Kelly'] },
  { tag: 'Angela',            label: 'Angela Martin',      patterns: ['Angela Martin', 'Angela'] },
  { tag: 'Kevin',             label: 'Kevin Malone',       patterns: ['Kevin Malone', 'Kevin'] },
  { tag: 'Oscar',             label: 'Oscar Martinez',     patterns: ['Oscar Martinez', 'Oscar'] },
  { tag: 'Phyllis',           label: 'Phyllis Vance',      patterns: ['Phyllis Vance', 'Phyllis'] },
  { tag: 'Creed',             label: 'Creed Bratton',      patterns: ['Creed Bratton', 'Creed'] },
  { tag: 'Andy',              label: 'Andy Bernard',       patterns: ['Andy Bernard', 'Andy'] },
  { tag: 'Toby',              label: 'Toby Flenderson',    patterns: ['Toby Flenderson', 'Toby'] },
  { tag: 'Meredith',          label: 'Meredith Palmer',    patterns: ['Meredith Palmer', 'Meredith'] },
  { tag: 'Stanley',           label: 'Stanley Hudson',     patterns: ['Stanley Hudson', 'Stanley'] },
  { tag: 'Darryl',            label: 'Darryl Philbin',     patterns: ['Darryl Philbin', 'Darryl'] },
  { tag: 'Jan',               label: 'Jan Levinson',       patterns: ['Jan Levinson', 'Jan'] },
  { tag: 'Holly',             label: 'Holly Flax',         patterns: ['Holly Flax', 'Holly'] },
  { tag: 'Roy',               label: 'Roy Anderson',       patterns: ['Roy Anderson', 'Roy'] },
  { tag: 'Erin',              label: 'Erin Hannon',        patterns: ['Erin Hannon', 'Erin'] },
  { tag: 'Gabe',              label: 'Gabe Lewis',         patterns: ['Gabe Lewis', 'Gabe'] },
  { tag: 'Robert California', label: 'Robert California',  patterns: ['Robert California'] },
  { tag: 'Karen',             label: 'Karen Filippelli',   patterns: ['Karen Filippelli', 'Karen'] },
  { tag: 'Todd Packer',       label: 'Todd Packer',        patterns: ['Todd Packer'] },
];

// ── PAUSE QUOTES ──────────────────────────────────────────────────
// Shown on the pause overlay during a party game.
const PAUSE_QUOTES = [
  { text: "Nobody panic. I have called a brief intermission. Life is a theater. Except right now it is paused. Like a theater, but the actors are just standing there.", character: "Michael Scott" },
  { text: "A good soldier knows when to hold position. We hold position. Nobody moves until I say.", character: "Dwight Schrute" },
  { text: "I just want to lie on the beach and eat hot dogs. That's all I've ever wanted.", character: "Kevin Malone" },
  { text: "In survival situations, a rest period of three to five minutes can mean the difference between life and death. This pause is tactical.", character: "Dwight Schrute" },
  { text: "I don't know what's happening, but I am very comfortable with it.", character: "Creed Bratton" },
  { text: "I am running away from my responsibilities. And it feels good.", character: "Michael Scott" },
  { text: "NARD DOG is patient. NARD DOG can wait. NARD DOG has nowhere to be.", character: "Andy Bernard" },
  { text: "I suppose there is value in stepping back and reassessing. Statistically speaking, people who pause make significantly better decisions.", character: "Oscar Martinez" },
  { text: "I am taking a mental health moment. Everyone should take mental health moments. Except Toby. His mental health is beyond help.", character: "Michael Scott" },
  { text: "If I had a gun with two bullets and I was in a room with Hitler, bin Laden, and someone interrupting my break... I'd just wait.", character: "Dwight Schrute" },
];

// ── TAG SUGGESTIONS FOR ADMIN ─────────────────────────────────────
const TAG_SUGGESTIONS = [
  "Michael", "Dwight", "Jim", "Pam", "Ryan", "Kelly", "Angela",
  "Kevin", "Oscar", "Phyllis", "Creed", "Andy", "Toby", "Meredith",
  "Stanley", "Darryl", "Jan", "Holly", "Roy", "Erin", "Gabe",
  "Robert California", "Karen", "Todd Packer", "Ryan", "Nellie",
  "Season 1", "Season 2", "Season 3", "Season 4", "Season 5",
  "Season 6", "Season 7", "Season 8", "Season 9",
  "Pranks", "Romance", "Fire", "Christmas", "Dundies",
  "Cold Open", "Quote", "Food", "Animals", "Finale", "Pilot",
  "Behind the Scenes", "Schrute Farms", "Benihana", "Stamford",
  "Fan Favorite", "Running Gag", "Improvised"
];
